### ISSUE TITLE
Automatic NuGet deployment when release is published

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1039]
Currently, when we make a new release, we manually trigger a NuGet deployment from AppVeyor. But AppVeyor also has an option to trigger a deployment when a new tag is pushed:
https://www.appveyor.com/docs/deployment/#deploy-on-tag-github-and-gitlab-only

This would make the release process even smoother, since publishing the release on GitHub would automatically build and deploy the packages.

Depends on #1046.

**Comment by blairconrad** [comment]
:+1:

**Comment by adamralph** [comment]
Since there was some concern in #1040 regarding automatic deployment WRT our current soluition for pre-releases, `VERSION_SUFFIX`, I suggest that we put this on holding pending:

- adopting gitflow
- adopting https://github.com/GitTools/GitVersion (which depends on adopting gitflow). This would remove the need for `VERSION_SUFFIX`.

**Comment by blairconrad** [comment]
Done, @adamralph.

**Comment by blairconrad** [comment]
We've adopted gitflow and gitversion. I think we can take this off-hold now.

**Comment by blairconrad** [comment]
In addition to deploying when a tag is pushed, we could also have AppVeyor attach the nupkgs to the GitHub Release.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.0.0).
