### ISSUE TITLE
Full argument report when ACallTo - MustHaveHappened fails. 

### ISSUE THREAD

**Issue by lisamariet** [FakeItEasy/FakeItEasy#1110]
I want: Better output in testrunner for when `A.CallTo(() => someMethod(ARGUMENT_MATCHING).MustHaveHappened` failes because not correct arguments was used.

I would love to actually get a full report on which params did not match whenever I write arguments to a method as `A.<MyClass>.That.Matches(c => c.bool == true && c.name == "correctName")`

So if a call to that method actually DID happen but the arguments did not match. I would love to actually see 
1 Call Was made to that method but with Not matching params. And then display all the params that WAS used in the call. 

So Excpected call to ...
But did not happen in Calls:
#1 with arguments used in that call
#2 with arguments used in that call

Hope this was understandable.

**Comment by blairconrad** [comment]
Hi, @lisamariet. Thanks for your interest in FakeItEasy.

If I understand correctly, you're interested in having more detailed information from `MustHaveHappened` when 

1. you use a custom argument matcher (`A<MyClass>.That.Matches(…)`)
2. a call _is_ made to the faked method, but
3. the call doesn't match because some subclause of the constraint is violated

I believe this is exactly the same as #1078 (Identify precise mismatch when a complex argument constraint fails to match an argument). Can you confirm? And if not, please guide us to the actual concern.

As you can see, we closed this issue with a "wontfix" designation due to the complexities of building a comprehensive message when multiple parameters are used and/or multiple calls are made.

A number of workarounds were discussed in the issue, including:

1. adding a description method to your argument type, either by providing a `ToString` implementation or using an [ArgumentValueFormatter](http://fakeiteasy.readthedocs.io/en/stable/formatting-argument-values/) and
2. [capturing the argument and interrogating it later](http://www.alexjamesbrown.com/blog/development/asserting-multiple-properties-argument-fakeiteasy/), as proposed by the issue-raiser, @alexjamesbrown

Thanks.

**Comment by lisamariet** [comment]
Well yes.. close anyway. I think I found that the answer is ArgumentValueFormatter.. I just need to understand it.. but that looks like what I want. I want the outputted arguments. 

Thanks alot!!! :-D

**Comment by blairconrad** [comment]
I'm glad it looks like it's going to help. I rarely need ArgumentValueFormatter, but when I do, I find it to be quite helpful. Happy FakeItEasying.

**Comment by lisamariet** [comment]
It worked like a charm!! :-D
