### ISSUE TITLE
Add a shorthand method to instantiate Fake objects

### ISSUE THREAD

**Issue by amoerie** [FakeItEasy/FakeItEasy#1201]
First of all, thanks for the great library! We use it extensively where I work.
This also means we've been spending some time on how to optimise writing our tests using FakeItEasy, and we came up with some utility methods that smoothen the process.

One of these is the use of extension methods to create Fake objects:

```csharp
  using FakeItEasy;

  public static class ExtensionsForT {
    public static T Fake<T>(this T reference) {
      return A.Fake<T>();
    }

    public static T Dummy<T>(this T reference) {
      return A.Dummy<T>();
    }
  }
```

What is the purpose of such a method, you may ask! Well, take the following example:

```csharp
  public class ISomethingGenericThatAlsoHasALongName<T> { }

  public class Foo<T>
  {
    private readonly ISomethingGenericThatAlsoHasALongName<T> _something;

    public Foo(ISomethingGenericThatAlsoHasALongName<T> something)
    {
      _something = something;
    }
  }

  public class FooTests
  {
    private ISomethingGenericThatAlsoHasALongName<List<string>> _bar;
    private Foo<List<string>> _foo;

    public FooTests()
    {
      // with the extension method
      _bar = _bar.Fake();
      
      // without the extension method
      _bar = A.Fake<ISomethingGenericThatAlsoHasALongName<List<string>>>()


      _foo = new Foo<List<string>>(_bar);
    }
  }
```

This makes use of the fact that extension methods work on NULL, which is great because we only want to capture the type information. 

Benefits:

- [x] Much faster to type (especially with generic types)
- [x] Works great with intellisense / Resharper / ...
- [x] Less work when you refactor
- [x] Easy to implement, two one liners

Downsides:

- Slightly counter intuitive  to call a method on an uninitialized field or variable
- Increases API surface of the library

We have been carrying these extension methods around in all our products for a few years now, and today I figured I would request if this could be put in the official library itself... 

Thank you for your consideration!

**Comment by thomaslevesque** [comment]
Hi @amoerie,

Thanks for the suggestion. That's a pretty clever idea! However, how much as I like it, I'm not sure it's a good fit for the library, because:
- as you mentioned, it's a bit counter-intuitive
- it adds extension methods to _all_ types, which adds noise to Intellisense, whether you want to use the methods or not.
- it's useful only for a use case (initializing a field of the test class) that is quite common, but not universal; lots of people just do `var foo = A.Fake<IFoo>()`.
- if you really want to use this, it's very easy to add it yourself to your test project, as you've been doing so far

@FakeItEasy/owners what do you think?

**Comment by amoerie** [comment]
Hi @thomaslevesque, thanks!

I definitely understand your concerns, as we shared some of them initially, but we concluded that

* we almost never use var foo = A.Fake<IFoo>()
* the counter-intuitive argument doesn't weigh up against getting used to writing and reading this. We have thousands upon thousands of tests across our products and FakeItEasy is (probably) used in almost every one of them. It becomes a matter of habit.
* we found it acceptable to have an extension method on _all_ types since it's only present inside isolated tests projects.

Of course, our needs and opinions may differ from others, I presume your judgement on these things wil be better than mine!

**Comment by thomaslevesque** [comment]
I guess I'd be _slightly_ more amenable to something like this:

    Fake.Create(ref _foo);
    Dummy.Create(ref _bar);

**Comment by blairconrad** [comment]
Thanks for the interest, @amoerie. It's an interesting idea. I don't want to quash your enthusiasm, but my feelings align very closely with @thomaslevesque's [first comment](https://github.com/FakeItEasy/FakeItEasy/issues/1201#issuecomment-331454976):

* I find the syntax confusing, and prefer more keystrokes and clear intent over fewer keystrokes and a (to me) unclear action
* I'm also not a fan of adding an extension method to all types. We've avoided API features in the past for this reason
* I (and I think others) use `var foo = A.Fake<IFoo>()` all the time. Which doesn't make it less useful for your case; it just helps judge the effect of the feature

@thomaslevesque, your alternative syntax is interesting. I prefer it to the original, although I would still be disinclined to include in core FakeItEasy. While we're here, why a `ref` and not an `out`?

@amoerie, if it turns out that we don't end up including something like your feature, have you considered producing your own NuGet package with it? It seems like it would be pretty easy, and then you could just include it in your projects and get FakeItEasy transitively, so you're not even increasing your NuGet management load.

**Comment by thomaslevesque** [comment]
> While we're here, why a ref and not an out?

No reason. It should be `out`, of course.

> @amoerie, if it turns out that we don't end up including something like your feature, have you considered producing your own NuGet package with it?

That's probably the best option 👍

**Comment by amoerie** [comment]
Well we already distribute a Nuget package in our internal company network that includes a bunch of testing related utilities, such as this one. So having to maintain a separate public one just for this is not really my intention. 

But thank you for considering it, I quite like the 'out' parameter thing as well, and that would even work with var declarations!

**Comment by blairconrad** [comment]
> Well we already distribute a Nuget package in our internal company network that includes a bunch of testing related utilities, such as this one. So having to maintain a separate public one just for this is not really my intention.

Ah, very good. My intention wasn't to force you to share your package with the world (not that there's anything wrong with that), but to explore easier ways for you to accomplish your goal within your company. It sounds like you're way ahead of me.

I think we've reached the end of the discussion, so I'll close the issue. If I'm wrong, please reopen.
And thanks again, @amoerie. We do appreciate your interest and are glad you enjoy FakeItEasy.
