### ISSUE TITLE
Consider changing AssemblyVersion to only include major version

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1209]
See #1208, https://github.com/castleproject/Core/issues/288 for details

In short, best practice is that FakeItEasy 4.x.y should always have 4.0.0.0 as the `AssemblyVersion`, in order to avoid assembly binding issues. `AssemblyFileVersion ` would still follow the package version (4.x.y.0).

**Comment by blairconrad** [comment]
As I understand this change, it will make it more convenient for clients of both FakeItEasy (FIE) and a FakeItEasy-using library (FUL) to upgrade FUL when the new version of FUL references a different (probably newer) version of FIE than the client wants to, yes?

I thought I saw a comment @thomaslevesque you that Castle.Core should probably have released 5.0.0.0 with this change, since it's breaking (and if nothing else, it looks weird, since the Assembly Version transitioned from 4.1 to 5.0), so should be [breaking](https://github.com/FakeItEasy/FakeItEasy/labels/breaking)?

**Comment by thomaslevesque** [comment]
> As I understand this change, it will make it more convenient for clients of both FakeItEasy (FIE) and a FakeItEasy-using library (FUL) to upgrade FUL when the new version of FUL references a different (probably newer) version of FIE than the client wants to, yes?

Exactly

> I thought I saw a comment @thomaslevesque you that Castle.Core should probably have released 5.0.0.0 with this change, since it's breaking (and if nothing else, it looks weird, since the Assembly Version transitioned from 4.1 to 5.0), so should be breaking?

Well, for us it wouldn't be breaking at this point, because we haven't released anything above 4.0.0 yet, so we won't need to "downgrade" the assembly version. Of course, to be non-breaking it *has* do be done for the next release.

**Comment by blairconrad** [comment]
> so we won't need to "downgrade" the assembly version. Of course, to be non-breaking it has do be done for the next release.

Understood. I'm on board.
