### ISSUE TITLE
4.2.0 Implicit conversion don't seem to be working

### ISSUE THREAD

**Issue by niemyjski** [FakeItEasy/FakeItEasy#1271]
I'm getting an error with the latest version that should work.
FakeItEasy.Configuration.FakeConfigurationException : Argument constraint is of type System.String, but parameter is of type Foundatio.Repositories.Id. No call can match this constraint.

https://github.com/FoundatioFx/Foundatio.Repositories/blob/master/src/Foundatio.Repositories/Id.cs#L20

I had GetByIdAsync(A<string>.Ignored) which was working for a long time.. changing it to GetByIdAsync(A<Id>.Ignored) made it go away.. I think this is a regression

**Comment by blairconrad** [comment]
Thanks for raising this, @niemyjski. I think you're describing #1237. This was an intentional change. I believe that your original call specifications would never have been matched, because the `id` is not a `string`, it's  an `Id`. This behaviour has been a source of errors in the past, so the fix to #1237 was to allert users when there was such a type mismatch.

**Comment by blairconrad** [comment]
Perhaps a more clear example. This test fails under FakeItEasy 4.1.1 because `DoIt` returns `false`.

```c#
public class Niemyjski
{
    public struct Id
    {
        public Id(string id) { }
        public static implicit operator Id(string id) => new Id(id);
    }

    public interface IIdOperator
    {
        bool DoIt(Id id);
    }

    [Fact]
    public void DefineBehaviourUsingStringParameterFails()
    {
        var fake = A.Fake<IIdOperator>();

        A.CallTo(() => fake.DoIt(A<string>._)).Returns(true);

        Assert.True(fake.DoIt(""));
    }
}
```

Under FakeItEasy 4.2.0, it gives the exception you noted:

```
Test 'FakeItEasyPlay.Niemyjski.DefineBehaviourUsingStringParameterFails' failed:
  FakeItEasy.Configuration.FakeConfigurationException :
    Argument constraint is of type System.String, but parameter is of type FakeItEasyPlay.Niemyjski+Id. No call can match this constraint.
```

Which has the advantage of telling the test-writer that the test is flawed, rather than just misleading them into thinking the faked method will behave in a way that it won't.

**Comment by niemyjski** [comment]
I just wanted to make sure this was intended. Perhaps this should have
bumped the version to 5.0 as it was a breaking change, but all is well :)

Thanks
-Blake Niemyjski

**Comment by blairconrad** [comment]
We consider it a non-breaking change since it only has an effect on existing code that is demonstrably incorrect, by exposing an existing bug in the test.

Thanks.
