### ISSUE TITLE
Bug - Configuring a property fails when using strict mode

### ISSUE THREAD

**Issue by JoeyPazone** [FakeItEasy/FakeItEasy#1340]
```
public interface IInterface
{
    int Number { get; set; }
}

public class Class1
{
    [Fact]
    public void Test1()
    {
        IInterface iInterface = A.Fake<IInterface>(options => options.Strict());
        iInterface.Number = 4; // Throws FakeItEasy.ExpectationException: "Call to unconfigured method of strict fake: IInterface.Number = 4."

        Assert.Equal(4, iInterface.Number);
    }
}
```

I don't have the capacity to fix it, I just wanted to report it.

Thanks!

**Comment by thomaslevesque** [comment]
This is by design. Strict mode disables all [default fake behaviors](http://fakeiteasy.readthedocs.io/en/stable/default-fake-behavior/), so all methods (including property setters and getters) throw if they're not explicitly configured. The [default behavior for read-write properties](http://fakeiteasy.readthedocs.io/en/stable/default-fake-behavior/#readwrite-properties) doesn't apply in strict mode (we should probably mention this explicitly in the documentation).

You can achieve the desired behavior by explicitly configure the property getter:

```csharp
A.CallTo(() => iInterface.Number).Returns(4);
```

**Comment by JoeyPazone** [comment]
Hi @thomaslevesque,
Thank you for your timely reply, however the code you suggested throws the same exception.

**Comment by thomaslevesque** [comment]
If you need to configure the behavior of the property setter, you can use `A.CallToSet(() => iInterface.Number).To(4).Invokes(...)`

**Comment by JoeyPazone** [comment]
I found my issue. When I was stepping through the code with the debugger, ReSharper was calling the getter for iInterface.Number before FakeItEasy had set it up, so that's why I was still seeing an exception. If I don't put a breakpoint on the line A.CallTo(() => iInterface.Number).Returns(4);, I don't see the exception.

Thank you for your help, and for pointing out that the default behavior for read-write properties doesn't apply in strict mode.

**Comment by thomaslevesque** [comment]
> When I was stepping through the code with the debugger, ReSharper was calling the getter for iInterface.Number

Ouch. That's bad... It must caused by the "data tips" feature they added in 2017.3. I didn't like it anyway, so I disabled it.

**Comment by JoeyPazone** [comment]
Yep, that's exactly what it was.
