### ISSUE TITLE
Be more strict with out of date pull requests

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1425]
@adamralph [suggested](https://github.com/FakeItEasy/FakeItEasy/pull/1421#issuecomment-417941849) we dismiss stale reviews.
Me, I don't understand why this isn't just _the way_.

@thomaslevesque, if you've no objection, I'll make the switch!

**Comment by thomaslevesque** [comment]
That makes sense, let's do it!

**Comment by blairconrad** [comment]
Done. Thanks.

And while I was there, I [enabled](https://github.com/FakeItEasy/FakeItEasy/settings/branch_protection_rules/20350)
"Require branches to be up to date before merging".
It makes sense to me, but if you prefer a looser setting, I will (or you can) disable.

**Comment by thomaslevesque** [comment]
> And while I was there, I enabled
> "Require branches to be up to date before merging".
> It makes sense to me, but if you prefer a looser setting, I will (or you can) disable.

👍

**Comment by adamralph** [comment]
Bear in mind that with "Require branches to be up to date before merging", all PR branches need to either be based on the tip of `develop`, or have the tip of `develop` merged into them (although I know the latter is not your workflow). That means you won't be able to accept a PR based on an older `develop` commit until it has been rebased. If contributors enable "Allow edits from maintainers" then you can do that rebase yourself, otherwise you will have to ask them to do it. IMO this introduces too much friction and I prefer to leave this setting disabled.

**Comment by blairconrad** [comment]
Thanks for the warning, @adamralph. I'd considered this, but really do like the idea of the warning (at least) that source has been updated underneath a PR, since (IIRC), AppVeyor isn't triggering a new build on the unmerged PR after another PR is merged.
We rarely have overlapping PRs that wouldn't end up being at least squashed anyhow, so the rebase shouldn't be too much effort.
If a git-naive contributor gets hit with this, we can always branch, cherry-pick, create a new PR and merge. Which is a small annoyance, but one I'd be happy to suffer, at least the once.

If the setting proves to be annoying, we can always revert.

**Comment by blairconrad** [comment]
Settings updated.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.8.1](https://github.com/FakeItEasy/FakeItEasy/releases/4.8.1).
