### ISSUE TITLE
Faked method calls within tasks don't get recognized by FakeItEasy all of the time

### ISSUE THREAD

**Issue by ToniRiegler** [FakeItEasy/FakeItEasy#1460]
There seems to be a bug using _MustHaveHappened_ in combination with _Tasks_.

Please see my gist:
https://gist.github.com/ToniRiegler/4812345401f582755e876349978151e2

It doesn't happen all of the time, but you can reproduce it easily using _NCrunch_ with _Churn selected test until it fails_ activated.

The Bug is reproducible with FakeItEasy 4.7.1 and 4.9.0 but not with FakeItEasy 2.3.1.

**Comment by thomaslevesque** [comment]
Hi @ToniRiegler,

Thanks for reporting, we'll look into it. Which framework are you targeting? .NET Framework, .NET Core ? Which version?

**Comment by ToniRiegler** [comment]
.NET Framework 4.7

**Comment by thomaslevesque** [comment]
I can repro after a few iterations (usually less than 50). Looks like a race condition where we record calls. But I'm not sure how it can happen... We're using a `ConcurrentQueue` for this, which should be perfectly thread-safe... Still looking.

**Comment by thomaslevesque** [comment]
OK, I found the root cause of the problem. The condition in the `Count` here:

https://github.com/FakeItEasy/FakeItEasy/blob/7a5fd74cb9131158b9dad69444d4c76541b3528e/src/FakeItEasy/Core/FakeAsserter.cs#L34

excludes the first call, because it has a higher sequence number than the second. This happens because of a race condition in `FakeManager.RecordCall`:

https://github.com/FakeItEasy/FakeItEasy/blob/7a5fd74cb9131158b9dad69444d4c76541b3528e/src/FakeItEasy/Core/FakeManager.cs#L179-L183

The race condition is something like this:

1. [Thread1] assign sequence number for call 1
1. [Thread2] assign sequence number for call 2
1. [Thread2] add call 2 to recorded calls
1. [Thread1] add call 1 to recorded calls

Possible fixes:

a. Put a lock around the two statements in `FakeManager.RecordCalls`. I tested it, it works, but it's not ideal as it might impact performance.
b. In `FakeAsserter.AssertWasCalled`, take the max sequence number instead of the last. Also tested, also works. Performance impact is probably smaller, unless there are many calls.
c. Keep track of the highest recorded sequence number for that fake. Almost no performance impact, but I'm not sure we can do it in a thread-safe way without using a lock.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.9.1](https://github.com/FakeItEasy/FakeItEasy/releases/4.9.1).

Thanks, @ToniRiegler! The reproduction instructions were excellent. Look for your name in the release notes. :trophy:

**Comment by ToniRiegler** [comment]
I'm glad you found it.
Thanks for new version and mention in the release notes.
