### ISSUE TITLE
Fake arguments on method calls outside of A.CallTo()

### ISSUE THREAD

**Issue by AMoghrabi** [FakeItEasy/FakeItEasy#1579]
Hello,

I'm upgrading a codebase that uses FakeItEasy v. 1.25.3 (👴 ) to the latest version. There are areas where `A<string>.Ignored` are used outside of a `A.CallTo()` expression. According to the documentation this is no longer allowed.

So far I've been replacing the code with `A.Dummy<string>()` and the tests are passing in some areas. In other areas creating a dummy object doesn't work so well,, such as `A.Dummy<XmlElement>()` will throw an exception -- it looks like I need to provide some extra configuration to the Dummy Factory. 

Can you please provide alternatives of what to use, if there is anything? My apologies if there is something in the docs that I overlooked. 

Thanks!

**Comment by blairconrad** [comment]
Hi, @AMoghrabi. Thanks for your interest in FakeItEasy. I'm sorry that the upgrade isn't going well for you.

The `A<T>.Ignored` was never intended to be used outside of a call specification, and didn't really have defined semantics. I believe in practice it ended up returning `default(T)`. For a reference type, this will be `null`.

Ultimately, I think you will have to examine your tests. In each case, you'll need to change the usage of `Ignored` into something that makes sense for the test - what do you need?

`A.Dummy` is appropriate if you really don't care what value the variable has. It will attempt to [create a non-null object using a few different creation strategies in turn](https://fakeiteasy.readthedocs.io/en/stable/dummies/#how-are-the-dummies-made).

However, as you've noted, not everything can be made into a Dummy out of the box, as the class's constructors may have additional requirements.

In some cases, the answer may be not to make a Dummy, but to create your object some other way. Maybe by parsing an XML literal to get a valid XmlElement (or if `null` works, you could use that, I suppose).

You may find that you have a consistent set of requirements for objects of a certain class, and then you could create a [Dummy Factory](https://fakeiteasy.readthedocs.io/en/stable/custom-dummy-creation/) that will produce such an item, but you'll have to provide your own logic to actually construct the instance.

I know this was a rambling and vague answer, but it really does depend on what you need for each test. If this doesn't help, please come back with more questions. Note that in order to give specific advice, we'll likely need to see some of your tests in order to understand exactly what you're trying to accomplish with each object-formerly-made-via-`Ignored`.

**Comment by AMoghrabi** [comment]
This is a great response, thanks @blairconrad. I believe the intention was the argument being passed in doesn't matter, so using `default(T)` and Dummy objects will work. I'll come back and provide some code if this doesn't work out.

Have a great weekend!

**Comment by blairconrad** [comment]
I'm glad it worked out for you, @AMoghrabi. Happy FakeItEasying.

**Comment by AMoghrabi** [comment]
Thanks again Blair!
