### ISSUE TITLE
Problem FakeItEasy Ninject WebServer

### ISSUE THREAD

**Issue by elkami** [FakeItEasy/FakeItEasy#1597]
on a unit test [TestClass]   i try to use Ninject and module fakeiteasy but the fakeiteasy dont respect singleton or current object, always create new (different hashcode) on a HttpServer local unit test calling internal with HttpClient, and creating fake object on [TestMethod]   things like MustHaveHappend Always fail but another object created and its called.

```
[TestInitialize]
kernel <-- fakeiteasy  (standarkernel load fakeiteasymodule)
kernel.bind<isomething>.ToMock().InSingletonScope();
config.DependencyResolver = new NinjectResolver(kernel);
HttpServer _server = new HttpServer(config); 
//using Effort too but out of scope here

[TestMethod]
client = new HttpClient(_server);
request = new HttpRequestMessage(); //uri, headers, method, etc
obj = kernel.Get<isomething>();
A.Call.obj ... DoesNothing(); //try with and without
using(response =client.SendAsync(request).Result)
{
   A.Call ... MustHaveHappend  <-- fail
}
```

if i debug and check HashCode when code execute de Controller on the webapi (project on same solution)  [run on the same process, same thread i think (checked on Thread window]   and on unittest method check hashcode and they are different objects.

**Comment by blairconrad** [comment]
Hi, @elkami. I'm sorry you're not having a good experience.

Am I right in thinking that you're using the Ninject.MockingKernel.FakeItEasy extension? I have no experience with it at all, but I'm still happy to try to help.

I must confess I'm a little lost. You seem to have mixed comments and pseudocode together (at least I think the `<--`s are comment indicators). Without seeing your actual code, I have very low faith that we'll be able to diagnose your problem. Can you post a small running (and failing) example, or failing that, at least as much of the original test and production code as possible? In these situations, it's often a very tiny detail that can make a difference between success and failure, and reading this redacted test may ruin our efforts.

**Comment by elkami** [comment]
sure, it was hard to explain, but i write a clean solution replicating the error.
i attached the project.     and add console output hashcode 
TestInit 54667902
TestMethod 54667902
Controller Const66772229
Controller Method 66772229
when is on controller, another fake empty object its created without functionality.  ( i cant inject stuff on the unit test method)

i hope with this simple example can understand the problem. 

[FakeItEasyProblemWebApi.zip](https://github.com/FakeItEasy/FakeItEasy/files/3432892/FakeItEasyProblemWebApi.zip)

**Comment by blairconrad** [comment]
Hi, @elkami. I see that the ninject extension will return the same instance when asked for two objects. This test passes:

```c#
[TestMethod]
public void TestSingletonWorks()
{
    var something1 = kernel.Get<ISomething>();
    var something2 = kernel.Get<ISomething>();
    Assert.AreSame(something1, something2);
}
```

As you say, the instance provided to the `public ValuesController(ISomething something)` constructor is _not_ the same one that's created in the test. I do not know why. I'm not familiar with AspNet.Mvc or whatever this framework is, but I'm trying to dig.

**Comment by blairconrad** [comment]
Ah. I made a guess, and it paid off a little. In `NinjectResolver`, I see

```c#
public IDependencyScope BeginScope()
{
    return new NinjectScope(_kernel.BeginBlock());
}
```

I thought that maybe making the new NinjectScope might interfere, and indeed if you remove the `.BeginBlock`, your original test passes - the same `ISomething` is used in the test and by the controller. The test outputs

```
TestInit 37421455
TestMethod 37421455
Controller Const37421455
Controller Method 37421455
```

Now, I definitely don't understand either Ninject or ASP.NET MVC, so I'm not sure how good an idea making this change is. maybe it's a terrible idea. I don't know.
But so far I don't see any evidence that FakeItEasy is doing anything wrong.

I think best to follow up at https://github.com/ninject/Ninject.MockingKernel/issues/38, which I've just now noticed you created as well. That would've been good information to have earlier.

**Comment by thomaslevesque** [comment]
I can confirm it has nothing to do with FakeItEasy. In fact, it doesn't even have anything to do with Ninject.MockingKernel: the same behavior can be observed without mocks, like this:

``` csharp
kernel.Bind<ISomething>().To<Something>().InSingletonScope();
```



> Now, I definitely don't understand either Ninject or ASP.NET MVC, so I'm not sure how good an idea making this change is.

I'm pretty sure it wouldn't do what @elkami had in mind, at least not on its own.

In ASP.NET (and probably many other backend frameworks), there's a notion of "request scope". When a service is registered with request scope, the IoC container will return the same instance during the processing of a given request, but a different one for each request. That's what the `IDependencyResolver.BeginScope` method means: begin a request scope in which a fresh instance of each "request-scoped" service will be created.

However, when a service is registered as a singleton, it should always return the same instance for all requests, regardless of scopes.

As far as I can tell, Ninject doesn't seem to support that. Even without the DependencyResolver infrastructure, just using `IKernel.BeginBlock()`, Ninject doesn't reuse instances of singletons but always create a new instance when in a new block. So... Maybe I'm missing something, but Ninject doesn't seem to properly handle the singleton lifetime, which is the simplest of all. Or, more likely maybe `BeginBlock` just isn't supposed to be used that way, and has nothing to do with "scopes" in the ASP.NET sense of the word.

Anyway, there is another package, Ninject.Web.Common, which adds an `InRequestScope` extension method for when you need a "request scoped" service, and doesn't seem to rely on `BeginBlock`. So if you use that, maybe your `IDependencyResolver` implementation could just return the kernel directly instead of creating a new block, as @blairconrad suggested. See [this page](https://github.com/ninject/Ninject.Web.Common/wiki/InRequestScope) for more details.

**Comment by elkami** [comment]
im new on Ninject and the FakeItEasyModule, then i used code example to make it all running.
And i was never do test like that for HttpServer to complete test the controller with a http request/response.   i was merging so many things news for me.
I apologize for my expertise and taking your time.  you both were extremely fast, concrete and nice with your check and conclusions.   Really appreciate it, you are amazing :D
I didnt have time to test it all together and do the changes, but are good fixes to my project and make the unit test works.

  im beginner on FakeItEasy but in the past i used RhinoMock (didnt test this with that framework) but when the creator say that unit test "doesnt have sense" and "abandon repo" (or thats i understand) [he really dont say it that way]. i was a banned unittest for a while, when im back i decide to use FakeItEasy and take me to here.

A good explanation for the Scope and why its creating different objects. thanks @blairconrad  and @thomaslevesque 
 
have  a good day

**Comment by blairconrad** [comment]
We're glad to do what we can, @elkami. Speaking for myself, I think there's still some value in unit testing (with mocks, even) as part of an overall testing regime.

Happy FakeItEasying!
