### ISSUE TITLE
Ease assertions with calls list

### ISSUE THREAD

**Issue by LukeMarlin** [FakeItEasy/FakeItEasy#1602]
[GetCalls](https://fakeiteasy.readthedocs.io/en/stable/advanced-usage/#getting-the-list-of-calls-made-on-a-fake) allows to get the call list of the faked object, however making your way through it isn't as friendly as the rest of the API.

As such, would it be possible to either:

- Add a `FakeItEasy.Configuration.IReturnValueArgumentValidationConfiguration.GetCalls()` method
or
- Add the `Fake.GetCalls(FakeItEasy.Configuration.IReturnValueArgumentValidationConfiguration)` overload

To immediately get the call list of a specifically setup call?

**Comment by blairconrad** [comment]
Thanks for your interest, @LukeMarlin. Can you given an example of how these would be used, contrasted with the current usage?

**Comment by LukeMarlin** [comment]
Indeed, sorry for not doing it before.

Common   setup:

```
var fake = A.Fake<FakeHttpMessageHandler>();
var callConfig = A.CallTo(() =>  fake.Send(A<HttpRequestMessage>.Ignored));
```

Current API:

```
var calls = Fake.GetCalls(fake).Where(c =>
   c.Method.Name == "x" &&
   c.Arguments.ArgumentNames.Contains("y")).ToList(); 
```

With the new overload:

```
var calls = Fake.GetCalls(callConfig).ToList();
```

With the new method:

```
var calls = callConfig.GetCalls().ToList();
```

Note that the "current API" sample doesn't match all the restrictions that can be set on the fake calls, it can be way more complicated than that to track down a specific call.

**Comment by blairconrad** [comment]
It's an intriguing idea. I was going to say I'd never felt a need, but probably in the past I've done something like configured a call to store its arguments in a list or something and interrogated the list later. With your approach, you could just interrogate the received arguments (so long as you're not looking at mutated reference types or something). It seems more direct.

I think I like the idea. @thomaslevesque, what think you?

**Comment by blairconrad** [comment]
Keying off `IReturnValueArgumentValidationConfiguration` (and similar interfaces/classes, as there's more than just `IReturnValueArgumentValidationConfiguration`) could be useful, but another  useful overload may be something like

```c#
var calls = Fake.GetCalls(() => fake.Send(A<HttpRequestMessage>.Ignored));
```

For the case where a Fake hasn't been previously-configured, or where the desired matcher hasn't already been defined.

Oh, and for what it's worth, I think I prefer this functionality to live on `Fake`, just like `GetCalls`, rather than on the configuration interfaces and classes.

**Comment by thomaslevesque** [comment]
Thanks @LukeMarlin for the suggestion. I like the idea too!

> but another useful overload may be something like
> 
> ```cs
> var calls = Fake.GetCalls(() => fake.Send(A<HttpRequestMessage>.Ignored));
> ```

Yes, that would be useful too.

> Oh, and for what it's worth, I think I prefer this functionality to live on `Fake`, just like `GetCalls`, rather than on the configuration interfaces and classes.

Agreed, but maybe it could also be exposed as extension methods on the configuration interfaces

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque.

@LukeMarlin, since you have an interest in this feature, do you want to give implementing it a shot? No pressure!

**Comment by LukeMarlin** [comment]
Thank you both for the quick response.
I've not yet looked at your code, so I've no idea if I would be able to help, I'd be glad to try though.
Don't hesitate to drop any ideas or hints you could have on your mind, that will probably prove helpful.

**Comment by blairconrad** [comment]
Great! Glad to have you aboard.

We have standard Github introductory articles at the top of the repo, like [how_to_build](https://github.com/FakeItEasy/FakeItEasy/blob/master/how_to_build.md) and [CONTRIBUTING](https://github.com/FakeItEasy/FakeItEasy/blob/master/CONTRIBUTING.md). Those should give you a quick start, I would think.

I find the hardest thing is deciding where to put the tests. I think next to [FakeSpecs.NonGenericCallsSuccess](https://github.com/FakeItEasy/FakeItEasy/blob/6ad1fffccb06c73415abf4c8137145050bb74b1f/tests/FakeItEasy.Specs/FakeSpecs.cs#L21) would be a good place, and you can use it as a model for your specs.

Documentation can be added to [advanced-usage.md](https://github.com/FakeItEasy/FakeItEasy/blob/02e6f4ef3e0ae49fdd3e712dd2e523a025a94d69/docs/advanced-usage.md#getting-the-list-of-calls-made-on-a-fake).

I guess we've never formalized the API.
Working on your and @thomaslevesque's comments, I'd think we'd want

* `Fake.GetCallsMatching(IArgumentValidationConfiguration<TInterface>)` (`IArgumentValidationConfiguration` is parent of `IReturnValueArgumentValidationConfiguration<T>` and `IVoidArgumentValidationConfiguration`)
* `Fake.GetCallsMatching(IPropertySetterConfiguration)`

with convenience methods being built up via

* `Fake.GetCallsMatching(Expression<Action> callSpecification)`,
* `Fake.GetCallsMatching(Expression<Func<T>> callSpecification)`, and
* `Fake.GetPropertySetCallsMatching(Expression<Func<TValue>> propertySpecification)` (I'm not sure about the name, but we need to differentiate from the previous one)

As @thomaslevesque says, we can augment these with extension methods on the configuration specification types if we like.

Oh. I used `GetCallsMatching` above to differentiate from `GetCalls`, since that takes an `object` and I've seen some confusion over `A.CallTo(object)` and `A.CallTo(Expression<…>)`. If you guys think there's no need, and prefer `GetCalls`, I'd reconsider.

This might be a little overwhelming. For now, I'd just pick a core method and write a test against it and implement. I'm happy to engage in as much dialogue as you want/need to make whatever level of contribution you want.

**Comment by thomaslevesque** [comment]
> I guess we've never formalized the API.
> Working on your and @thomaslevesque's comments, I'd think we'd want
> 
>     * `Fake.GetCallsMatching(IArgumentValidationConfiguration<TInterface>)` (`IArgumentValidationConfiguration` is parent of `IReturnValueArgumentValidationConfiguration<T>` and `IVoidArgumentValidationConfiguration`)
> 
>     * `Fake.GetCallsMatching(IPropertySetterConfiguration)`

Why not just accept a `IAssertConfiguration`? I think all configuration interfaces that fully specify a call inherit from `IAssertConfiguration`. Basically, if you can do `config.MustHaveHappened()`, you should also be able to do `Fake.GetCallsMatching(config)`, no?

**Comment by thomaslevesque** [comment]
Looking at this issue again, I realize there's already a feature in FakeItEasy to help with this: the `Matching` extension method. It can be used like this:

```csharp
var calls = Fake.GetCalls()
  .Matching(fake => fake.Send(A<HttpRequestMessage>.Ignored))
  .ToList();
```

So, the requested feature actually already exists, and has existed since v1! But somehow we never thought about it when discussing this issue.

Anyway, I think we can close this.
