### ISSUE TITLE
How do you upgrade the 'conditionally throw pattern' to 5.2?

### ISSUE THREAD

**Issue by TimLovellSmith** [FakeItEasy/FakeItEasy#1635]
What is the recommended pattern in 5.2 to achieve this?

```
var tryGetLongRunningOperation = A.CallTo(() => rdbStore.GetLongRunningOperation(A<string>.Ignored, A<string>.Ignored));
                tryGetLongRunningOperation.ReturnsLazily<LongRunningOperation, string, string>(
                    (string requestId, string operation) =>
                    {
                        if (requestId.Contains("1"))
                        { throw new LongRunningOperationDoesntExistException(); }
                        else if (requestId.Contains("2"))
                        { return GetLongRunningOperation("2", LongRunningOperationStatus.Successful); }
                    }
                );
```

5.2 unexpectedly turns this into "FakeItEasy.UserCallbackException: Return value producer threw an exception. See inner exception for details. ---> "

Which breaks all the expectations of the other exception handling code in between.

**Comment by TimLovellSmith** [comment]
Never mind, I guess this is a dupe of https://github.com/FakeItEasy/FakeItEasy/issues/1543

**Comment by thomaslevesque** [comment]
Hi @TimLovellSmith,

That's interesting... We introduced this change in #1364, because exceptions thrown in user-provided callbacks were typically hard to diagnose. But we didn't anticipate that kind of usage, where the `ReturnsLazily` callback throws *intentionally*...

For now, the workaround is to separately configure the case where you want to throw, using `Throws`:

```csharp
A.CallTo(() => rdbStore.GetLongRunningOperation(A<string>.Ignored, A<string>.Ignored))
    .ReturnsLazily((string requestId, string operation) =>
                    {
                        if (requestId.Contains("2"))
                        { return GetLongRunningOperation("2", LongRunningOperationStatus.Successful); }
                        // (I believe you're missing something here, since not all code paths return a value...)
                    });

A.CallTo(() => rdbStore.GetLongRunningOperation(A<string>.That.Contains("1"), A<string>.Ignored))
    .Throws<LongRunningOperationDoesntExistException>();
```

I must admit it's not a great experience...

@blairconrad this is similar to #1543, where we decided to revert the change for `Invokes`. Perhaps it would make sense to do the same for the `ReturnsLazily` callback, which can also be used as the faked method's body...

In fact, looking again at the checklist in #1364, I think maybe we shouldn't have done it for the "Call configuration APIs" items (except maybe for `Throws` which is supposed to return an exception, not throw it... although I guess we could just let the thrown exception bubble, which would have the same effect). Exceptions from "call specification" callbacks (`Where`, `WhenArgumentsMatch`...) are often hard to diagnose, and there's no good reason to ever throw intentionally from those callbacks; which was the main reason for doing #1364. But exceptions thrown from "action" callbacks (`ReturnsLazily`, `Invokes`...) can be intentional, like in this issue and in #1543. It used to be possible to either return something or throw an exception in `ReturnsLazily`, and we unintentionally removed that possibility. I think we should at least consider reverting that change.

> Never mind, I guess this is a dupe of #1543

It's similar, but not exactly the same... #1543 was about `Invokes`, which we reverted to its previous behavior. But we didn't revert `ReturnsLazily` (yet?), so I'll keep this issue open for now.

**Comment by TimLovellSmith** [comment]
The validation seems nice to have since I don't usually throw in ReturnsLazily... Maybe you could have a more intentional escape route, like 'ReturnsOrThrowsLazily', and mention it as part of the 'UserCallbackException' error message? (My initial reaction to seeing UserCallbackException was to read the error message, and then check in intellisense to see just in case you'd added some new API I should use instead)

**Comment by blairconrad** [comment]
@TimLovellSmith, I understand the desire to have something like `ReturnsOrThrowsLazily`, but I am not excited about the explosion of methods: `InvokesOrThrowsLazily`, `DoesNothingOrThrowsLazily`, `AssignsOutAndRefParametersOrThrowsLazily`, `ThrowsOrThrowsLazily`…, so I think we should consider other options.

I was about to propose something along the lines of @thomaslevesque's alternative, although I would've unpacked even more:

```c#
A.CallTo(() => rdbStore.GetLongRunningOperation(A<string>.Ignored, A<string>.Ignored))
    .ReturnsLazily((string requestId, string operation) => GetTheThingThatThomasLevesqueNoticedYouWereMissing());
A.CallTo(() => rdbStore.GetLongRunningOperation(A<string>.That.Contains("1"), A<string>.Ignored))
    .Throws<LongRunningOperationDoesntExistException>();
A.CallTo(() => rdbStore.GetLongRunningOperation(A<string>.That.Contains("2"), A<string>.Ignored))
    .ReturnsLazily((string requestId, string operation) => GetLongRunningOperation("2", LongRunningOperationStatus.Successful));
```

The repetition is annoying, but I like the explicitness up front. Someone reading the test will know when you throw and when you return something.
Of course tastes vary, and  you were probably hoping to use `tryGetLongRunningOperation` for later…

Still, I think it would be better to refrain from wrapping exceptions that arise from "action" callbacks. As @thomaslevesque hints at, it's easier to diagnose accidental exceptions from "action" callbacks than from the matchers.

**Comment by thomaslevesque** [comment]
Closing in favor of #1640
