### ISSUE TITLE
What is the generic CallTo<> used for?

### ISSUE THREAD

**Issue by silkfire** [FakeItEasy/FakeItEasy#1809]
I haven't been able to find any examples on uses for the version of `CallTo` that requires a `Func<T>` parameter. What is the use for this method?

Example:

```csharp
A.CallTo<T>(T x => ...)
```

**Comment by blairconrad** [comment]
Hi, @silkfire. Thanks for your interest. I think you're asking about

```c#
public static IReturnValueArgumentValidationConfiguration<T> CallTo<T>(Expression<Func<T>> callSpecification)
```

It's used quite frequently, in my experience. It might actually be the most popular `A.CallTo`! The `Expression<Func<T>>` is required to allow one to construct lines like

```c#
A.CallTo(() => fake.AMethodThatReturnsSomething()).Returns("something");
```

(and many variations). If we just had the  `Expression<Action>` overload, the C# or VB compilers would not find a match. Also this variation returns a `IReturnValueArgumentValidationConfiguration<T>`, which means the FakeItEasy fluent API can offer a richer experience, making the `.Return` legal when dealing with a method (or property) that return a value. This way the compiler catch errors for us, rather than waiting until runtime. Using `A.CallTo` on a void-returning would not offer the ability to add a `.Returns`.

**Comment by thomaslevesque** [comment]
In addition to what @blairconrad said: You never see `A.CallTo<T>(...)` in examples (or in your own code), because the compiler automatically infers the type of `T` based on what the lambda returns. It's just like Linq methods: you never where `.Where<T>(predicate)`, juste `.Where(predicate)`

**Comment by silkfire** [comment]
I feel so dumb right now! And I did realize that my example was wrong. A `Func<T>` returns a `T`, and does not use `T` as its only argument 😅 And of course, @thomaslevesque I now understand that the generic argument would be inferred and that's the reason it's not explicitly written out in any documentation.

**Comment by thomaslevesque** [comment]
There are no silly questions! Glad we were able to clarify this for you.

**Comment by blairconrad** [comment]
@silkfire , just as @thomaslevesque said, this was not silly at all. If you wondered, someone else probably did too. Now they have a resource. Happy FakeItEasying.
