### ISSUE TITLE
Fake properties contain not null value

### ISSUE THREAD

**Issue by Ed-Pavlov** [FakeItEasy/FakeItEasy#1824]
Checking for equality to null of interface's "fake" property returns false. It forces to set null value explicitly to properties if BL code checks them for null.
```
// declaration
public interface IBuildSession
  {
    [CanBeNull]
    BuildResult BuildResult { get; set; }
  }
  
// test code
  var buildSession = A.Fake<IBuildSession>();

  // --act
  target.Process(buildSession);
  
// Process method code
if (buildSession.BuildResult is null) // is always false, because Fake's BuildResult property is not null
```

**Comment by thomaslevesque** [comment]
Hi @Ed-Pavlov,

Thanks for your interest in FakeItEasy.

The behavior you describe is by design, and is described [here](https://fakeiteasy.readthedocs.io/en/stable/default-fake-behavior/#overrideable-members-are-faked). NSubstitute does the same thing, as far as I can tell, although Moq doesn't.

In most situations, this makes things easier, because you don't need to explicitly configure every property on faked types. In your case though, it's not what you want, so you'll need to explicitly set `buildSession.BuildResult` to null. If you need to do that often and want `BuildResult` to always be null initially, you can use [implicit creation options](https://fakeiteasy.readthedocs.io/en/stable/implicit-creation-options/) to configure every fake `IBuildSession` implicitly:

```csharp
public class BuildSessionFakeOptionsBuilder : FakeOptionsBuilder<IBuildSession>
{
    protected override void BuildOptions(IFakeOptions<IBuildSession> options)
    {
        options.ConfigureFake(fake =>
        {
            fake.BuildResult = null;
        });
    }
}
```

**Comment by Ed-Pavlov** [comment]
Thanks a lot for a quick answer. I've already realized that it is made on purpose and already found AutoFakePropertyRule, but have not found how to switch it off :) So, your answer is very helpful!
