### ISSUE TITLE
Initializing read only property of faked object does not work

### ISSUE THREAD

**Issue by Bludator** [FakeItEasy/FakeItEasy#1854]
I have been playing with fakes with `WithArgumentsForConstructor` and I found it very confusing.

First of all [the documentation](https://fakeiteasy.readthedocs.io/en/stable/creating-fakes/#explicit-creation-options):

> // Specifying arguments for constructor using expression. This is refactoring friendly!
> // The constructor seen here is never actually invoked. It is an expression and it's purpose
> // is purely to communicate the constructor arguments which will be extracted from it
> var foo = A.Fake<FooClass>(x => x.WithArgumentsForConstructor(() => new FooClass("foo", "bar")));

If one doesn't read carefully one could think that the constructor is never called and that is not true. There is even [SO question.](https://stackoverflow.com/questions/36972434/withargumentsforconstructor-extension-method-calls-constructor)
Actually the docs never say that the constructor runs (or not).

Secondly, when the constructor is called it is not possible to initialize faked (virtual/abstract) property.

Minimal (non)working example:

```C#
using FakeItEasy;
using Xunit;

public class Foo
{
	public virtual string VirtualProperty { get; }
	public virtual string VirtualPropertyWithSetter { get; set; }
	public string NotVirtualProperty { get; }
	public string NotVirtualPropertyWithSetter { get; set; }

	public Foo()
	{
		VirtualProperty = "my string"; // does nothing
		NotVirtualProperty = "my string";
		VirtualPropertyWithSetter = "my string";
		NotVirtualPropertyWithSetter = "my string";
	}
}

public class UnitTest
{
	[Fact]
	public void Test1() => Assert.Equal("my string", A.Fake<Foo>().VirtualProperty); //not passing

	[Fact]
	public void Test2() => Assert.Equal("my string", A.Fake<Foo>().VirtualPropertyWithSetter);

	[Fact]
	public void Test3() => Assert.Equal("my string", A.Fake<Foo>().NotVirtualProperty);

	[Fact]
	public void Test4() => Assert.Equal("my string", A.Fake<Foo>().NotVirtualPropertyWithSetter);
}
```

### Versions:
- FakeItEasy: 7.1.0
- .NET: 5.0

**Comment by thomaslevesque** [comment]
Hi @Bludator,

Thanks for the report.

You're right about the documentation, it's confusing and should probably be improved. It's true that the expression passed to `WithArgumentsForConstructor` isn't directly invoked, but it's used to specify the values that will be passed in the actual constructor call (so yes, obviously, the constructor *is* called at some point).

Regarding the problem with virtual properties, I understand why it doesn't work for `VirtualProperty`: properties without setters can be set in the constructor, but it's actually syntactic sugar: the compiler actually generates code that sets the *backing field* of the property, not the property itself. And since fields can't be virtual, FakeItEasy can't intercept that call. However, since the property is virtual, it does override the setter with a default behavior, which *doesn't* return the value of the backing field...

Basically, you end up with something like this:

```csharp
// Your original class, as the compiler actually generates it
public class Foo
{
        private readonly string _virtualPropertyBackingField;
	public virtual string VirtualProperty => _virtualPropertyBackingField;

        // Other properties omitted for brevity

	public Foo()
	{
		_virtualPropertyBackingField = "my string"; // does nothing
		// Other properties omitted for brevity
	}
}

// The fake generated by FakeItEasy
public class FakeFoo : Foo
{
        public override string VirtualProperty => string.Empty;
        // Other properties omitted for brevity
}
```

The easiest way to fix this is to specify `CallsBaseMethods()` in the fake creation options:

```csharp
A.Fake<Foo>(o => o.CallsBaseMethods())
```

This way, the default implementation for overridden methods (including property accessors) will be to call the base implementation, which will give you the expected behavior.

As a side note: calling virtual members in the constructor is generally [not a good idea](https://stackoverflow.com/q/119506/98713)...

**Comment by thomaslevesque** [comment]
Oh, and it *does* work for `VirtualPropertyWithSetter`, because we apply the [default behavior for read-write properties](https://fakeiteasy.readthedocs.io/en/stable/default-fake-behavior/#readwrite-properties)
