### ISSUE TITLE
Ignoring out/ref parameters

### ISSUE THREAD

**Issue by Ed-Pavlov** [FakeItEasy/FakeItEasy#1857]
If there is no need to mock out/ref parameter with the real value suggested ways to operate with them is not convinient. It would be better to use the way already used for normal parameters.

```
void Bar(string s, out int i)...

A.CallTo(() => foo.Bar("hello", out A<int>.Ignored)).MustHaveHappened();
```

Unfortunately both `A<T>._` and `A<T>.Ignored` are properties rather than fields and can't be used as an out parameter.

My suggestion:

- Turn `A<T>.Ignored` into the public field. I don't see why it should be the real constraint due to passed predicate always returns `true` and all other constraint behaviour is always ignored.
OR (I like it less, but still)
- Add public fields `A<T>.Out` `A<T>.Ref` - or any other name you find suitable.

If one of this suggestions would be approved I could create a pull request.

**Comment by blairconrad** [comment]
Thanks for the suggestion @Ed-Pavlov. `Ignored` is a property because its execution actually (through `.Matches`) calls [ReportTrappedConstraint](https://github.com/FakeItEasy/FakeItEasy/blob/61b23f7803d957093ebaba399aa23386145b9452/src/FakeItEasy/Core/ArgumentConstraintTrap.cs#L20). It's a sort of side effect that lets FakeItEasy know that a special constraint has been requested, rather than something like an exact match. 

Replacing `Ignored` with a field will thus break the functionality.
Were there a way to simplify the syntax without having detrimental effects on the rest of the system, we'd be interested, though!

**Comment by thomaslevesque** [comment]
The current way to handle this (declare the out variable outside the expression) isn't perfect, but IMHO it's not terrible either.
The best way would be if C# expression trees supported discards, then we could just do this:
```csharp
A.CallTo(() => foo.Bar("hello", out _)).MustHaveHappened();
```
Unfortunately expression trees haven't been updated to support any new features since C# 3...

**Comment by blairconrad** [comment]
I don't think there are likely to be any changes to this in the near future. We can always reopen, but for now I'm going to close the discussion.
