### ISSUE TITLE
Endless loop when using Automapper on faked IQueryable<T>

### ISSUE THREAD

**Issue by marcwittke** [FakeItEasy/FakeItEasy#1859]
Unsure, whether this is an issue with FakeItEasy or Automapper (or even Castle Proxy). 

Assuming an `IQueryable<Entity>` that is mapped using Automapper into an `IQueryable<EntityDto>` by means of their expression mapping extension. When the original queryable is mocked using FakeItEasy, the enumeration of the mapped queryable never returns. It hogs a CPU at 100%, so I am assuming some kind of endless loop.

```csharp
public class FakeItEasyTest
{
    private readonly Mapper _mapper;
    private readonly IQueryable<Entity> _queryable;

    public FakeItEasyTest()
    {
        _mapper = new Mapper(new MapperConfiguration(cfg => cfg.CreateMap<Entity, EntityDto>()));
        _queryable = A.Fake<IQueryable<Entity>>();
    }

    [Fact]
    public void CanEnumerateQueryable()
    {
        Assert.Empty(_queryable.ToArray());
    }

    [Fact]
    public void CanEnumerateDataSourceQueryable()
    {
        IQueryable<EntityDto> mappedQueryable = _queryable.UseAsDataSource(_mapper.ConfigurationProvider).For<EntityDto>();

        // never returns!
        Assert.Empty(mappedQueryable.ToArray());
    }

    [Fact]
    public void CanEnumerateProjectedQueryable()
    {
        // never returns!
        IQueryable<EntityDto> mappedQueryable = _queryable.ProjectTo<EntityDto>(_mapper.ConfigurationProvider);
        Assert.Empty(mappedQueryable.ToArray());
    }
}
```

repo: https://github.com/marcwittke/FakeItEasyVsAutoMapper

**Comment by blairconrad** [comment]
Hi, @marcwittke. Sorry to hear you're having a bad time. Thanks for the excellent repro. It was easy to build I see the same result you do.

That being said, I've not gotten any further. I am not an AutoMapper user, nor `IQueryable`, so I have no experience to bring to bear. I'd initially thought that I could just debug into `ProjectTo` (for example) and see what was going wrong, but I've not been able to step into the method. I even tried grabbing AutoMapper and referencing the project instead of the package, but so far no luck. I may continue off and on in the near future, but let's take a different tack.

My gut tells me to say that it's not a FakeItEasy bug, mostly because I see no evidence for it yet. FakeItEasy makes some promises about [how a faked interface behaves](https://fakeiteasy.readthedocs.io/en/stable/default-fake-behavior/), and I think they're being met. When I look at `_queryable` in the debugger, I see that 

* `ElementType` returns a fake `Type` (with Name "" and FullName "")
* `Expression` returns a fake  `Expression` 
* `Provider` returns a fake `IQueryProvider`
* `GetEnumerator` returns a fake `IEnumerator` whose `Current` is a fake `Entity` and whose `MoveNext` returns `false`

It all looks as expected. Now what AutoMapper's doing with that, I haven't been able to see with debugging, nor have I taken the time to pore through the code, effectively playing the role of the computer. 

I doubt I will have significant amounts of time to learn the AutoMapper internals in the near future. Perhaps you'd like to try debugging in?

As an aside, I don't see a lot of benefit in faking an `IQueryable` without customizing it. _Best case_, I'd expect it would act like an empty `IQueryable`. In which case, you might be better off explicitly making an empty `IQueryable` and returning that:

```c#
_queryable = Enumerable.Empty<Entity>().AsQueryable();
```
(Or configuring whatever IQueryable-returning Fake you have to return that.)

If that's a reasonable workaround for you, you could even make it more convenient by introducing a [Dummy Factory](https://fakeiteasy.readthedocs.io/en/stable/custom-dummy-creation/) to ensure this is how IQueryable return values (or parameters) are created by default.

Anyhow, I'm happy to continue the conversation as time allows. Tell us what you think.

**Comment by thomaslevesque** [comment]
Hi @marcwittke,

I'm not sure what's causing the infinite loop, but I wouldn't expect this to work anyway. `IQueryable<T>` is a strange beast, and it's difficult to mock correctly. In this case, you haven't configured the fake `IQueryable<T>` at all, so I don't think it's in a usable state.

I've had some luck with [MockQueryable](https://github.com/romantitov/MockQueryable/), maybe you could give it a try?

Anyway, I agree with @blairconrad's analysis: it's probably not a bug in FakeItEasy itself. In fact, I think it's also not a bug in Castle.Core or AutoMapper. It's just that the fake `IQueryable<T>` isn't configured properly.

**Comment by thomaslevesque** [comment]
You can use MockQueryable like this:

```csharp
var queryable = Enumerable.Empty<Entity>().AsQueryable().BuildMock();
```

(just replace `Enumerable.Empty<T>()` with whatever you want the queryable to contain)

**Comment by blairconrad** [comment]
@marcwittke, I'm sure you'll get your configuration working, but if you're interested, I stole some minutes to implement a DummyFactory that you might enjoy. It seemed to do the trick fo rme.

```c#
public class DummyQueryableFactory : IDummyFactory
{
    public bool CanCreate(Type type)
    {
        if (type.IsGenericType)
        {
            var queryableContentType = type.GetGenericArguments()[0];
            var queryableTypeDefinition = typeof(IQueryable<>).MakeGenericType(queryableContentType);
            return queryableTypeDefinition.IsAssignableFrom(type);
        }
        return false;
    }

    public object Create(Type type)
    {
        var queryableContentType = type.GetGenericArguments()[0];
        var listType = typeof(List<>).MakeGenericType(queryableContentType);
        var list = (IEnumerable)Activator.CreateInstance(listType);
        return Queryable.AsQueryable(list);
    }

    public Priority Priority
    {
        get { return Priority.Default; }
    }
}
```

**Comment by marcwittke** [comment]
Works like a charm, @blairconrad . Thanks, I updated the repro-repo that passes all tests now, even when there is an arbitrary interface faked that has a method returning IQueryable. 

I made an attempt with a dummy factory before, but obviously I was missing something. Well, it got pretty late yesterday... 

Thanks!
