### ISSUE TITLE
Explicitly support .NET 6.0 

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1873]
[.NET 5.0 Will reach end of life in May](https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/).

I'm not saying we should necessarily drop 5.0, but 6.0 is the LTS version, and if people are building 6.0 apps, it might be nice to target it.

**Comment by blairconrad** [comment]
@thomaslevesque, wanna tell me why this isn't necessary? Something like "oh, 6.0 apps will pick up the 5.0 libraries anyhow, but with updated, secure dependencies"?

**Comment by SimonCropp** [comment]
on point of value for targeting net6 is u get all the nullability hints that exist in net6 but not in net5

**Comment by blairconrad** [comment]
I was curious about what nullability hints we're missing out on, so I tried it out and opened #1875, just for discussion.
None came up! But we can all of a sudden fake interfaces that include methods with in parameters of a generic type. (Maybe we got that just from testing on 6.0, and producing a 6.0-targeting package was immaterial.)

**Comment by thomaslevesque** [comment]
> But we can all of a sudden fake interfaces that include methods with in parameters of a generic type.

That's great news!

> (Maybe we got that just from testing on 6.0, and producing a 6.0-targeting package was immaterial.)

Indeed. I just tested the current FakeItEasy version in a .NET 6 project, and this scenario works. I think it's because of [this fix](https://github.com/dotnet/runtime/pull/40587).

I think we should at least add a .NET 6.0 target for tests, since it allows us to cover this case. I'm still not convinced it's useful to produce a 6.0 package, though; it would be virtually identical to the 5.0 package, with no added benefit.

**Comment by blairconrad** [comment]
Split off #1876 for the "testing" portion of this issue. Perhaps we should close this one wontfix?

**Comment by thomaslevesque** [comment]
Sounds good to me! I'll close this one.
