### ISSUE TITLE
Equivalent to Moq's It.IsAnyType

### ISSUE THREAD

**Issue by IUnknownPtr** [FakeItEasy/FakeItEasy#1884]
Is there an equivalent to Moq's `It.IsAnyType`?

I want to mock `ILogger` calls generated by [source code generator](https://learn.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator).

``` c#
public interface ILogger
{
    void Log<TState>(
        Microsoft.Extensions.Logging.LogLevel logLevel,
        Microsoft.Extensions.Logging.EventId eventId,
        TState state,
        System.Exception? exception,
        Func<TState, System.Exception?, string> formatter);
}
```

`TState` is using an internal type that I can't declare in `A<>.Ignored` and there's no way to specify `Func<AnyType, ...>`.

**Comment by thomaslevesque** [comment]
Hi @IUnknownPtr,

Thanks for your question. Sadly, no, there's no equivalent to Moq's `It.IsAnyType`. `ILogger` is the archetypal use case. We've been [thinking for a while about the best way to mock generic methods](https://github.com/FakeItEasy/FakeItEasy/issues/743), but never settled on a solution. I'm not sure if we ever considered taking a page from Moq's book here... Maybe that's something we should revisit.

In the meantime, yes, mocking `ILogger` is a bit of a mess... I usually don't bother. If you really need to do this, you can do something like this:

```csharp
A.CallTo(logger)
 .Where(call => call.Method.Name == nameof(ILogger.Log))
 ...
```
Unfortunately, I can't think of an easy way to add constraints on the message... IMHO, Microsoft kinda messed up with this abstraction, making it almost impossible to test (especially since they switched to a non-public type for `TState`...)

**Comment by thomaslevesque** [comment]
Repeating my comment from #743 

> I attempted to implement this a while ago, and encountered some serious roadblocks. Doing this would require some _major_ refactoring, for a rather limited benefit.
> 
> The main (only?) use case we've seen so far is to assert calls to `ILogger`. However, since the commonly used logging methods are extension methods, we can't assert them directly, we need to assert the actual `ILogger.Log method` instead. So even if `FormattedLogValues` was public, or if we had something like Moq's `It.IsAnyType`, it would still be pretty inconvenient.
> 
> A better approach for testing logging is to use a fake logger that records the log entries. Microsoft provides one [here](https://github.com/dotnet/extensions/tree/main/src/Libraries/Microsoft.Extensions.Diagnostics.Testing).
> 
> Closing this for now. We can reopen if there's legitimate interest for it.
