### ISSUE TITLE
Test fails on Version 8 but succeeds on Version 7

### ISSUE THREAD

**Issue by joergpichler** [FakeItEasy/FakeItEasy#1988]
I just tried upgrading our solution from FakeItEasy version 7 to version 8 and I have reproduced our issue by this sample:

```
public interface IFoo : IReadOnlyCollection<object>
{
}

public interface IFooMatcher
{
    bool Matches(IFoo foo);
}

public class TestClass
{
    [Test]
    public void TestMethod()
    {
        var context1 = A.Fake<IFoo>();
        var context2 = A.Fake<IFoo>();

        var extractor = A.Fake<IFooMatcher>();
        A.CallTo(() => extractor.Matches(context1)).ReturnsLazily(_ => false);
        A.CallTo(() => extractor.Matches(context2)).ReturnsLazily(_ => true);

        Assert.That(extractor.Matches(context1), Is.False);
    }
}
```

I get that it has to do with the change of how collections are handled in the framework its obviously an issue in this context. Just because the inheritance hierarchy includes a collection type makes the test fail. In the production scenario two different (empty) objects would also behave differently.

Any suggestions how to handle this in a clean way?

**Comment by thomaslevesque** [comment]
Hi @joergpichler,

Indeed, the behavior for matching collection arguments has changed in v8. We believe that the new behavior is what people actually want in most cases, but it was inevitable that it was going to break some scenarios, unfortunately.
What you want in this case is to do a reference comparison, instead of comparing the contents of the collections:

```csharp
A.CallTo(() => extractor.Matches(A<IFoo>.That.IsSameAs(context1))).ReturnsLazily(_ => false);
A.CallTo(() => extractor.Matches(A<IFoo>.That.IsSameAs(context2))).ReturnsLazily(_ => true);
```

(also, not sure why you're using `ReturnsLazily` instead of just `Returns`... but maybe that's just a simplified version of your code)

> Just because the inheritance hierarchy includes a collection type

Well, implementing a collection interface effectively makes your type a collection. If it's intended to behave as something other than a collection, I'd consider not implementing the collection interface, but instead exposing a collection as a property or method. Obviously I don't know the context of your project, so it might not be applicable to you.

**Comment by joergpichler** [comment]
Hi @thomaslevesque ,

thanks that's of course the simplest fix, of course I did not think of that and fixed it by doing the comparison in the lambda function like
```
A.CallTo(() => extractor.Matches(context1)).ReturnsLazily((IFoo f) =>
{
    if (f == context1) return false;
    if (f == context2) return true;
    throw new InvalidOperationException();
});
```
To answer your other non related questions
- I have used `ReturnsLazily ` because I used breakpoints in there to debug the issue and never changed it back.
- I agree that exposing a collection would be better but thats how the system was designed ¯\_(ツ)_/¯

Thanks again.

**Comment by thomaslevesque** [comment]
I was just thinking, `A<IFoo>.That.IsSameAs(context1)` is pretty verbose. If you use it often, you might want to declare a helper method like this:

```csharp
static class Helpers
{
  public static T ByRef<T>(T value) where T : class
  {
    return A<T>.That.IsSameAs(value);
  }
}
```
(the name isn't great, but you can pick any name you like...)

And use it like this:

```csharp
using static MyNamespace.Helpers;

...

A.CallTo(() => extractor.Matches(ByRef(context1))).ReturnsLazily(_ => false);
A.CallTo(() => extractor.Matches(ByRef(context2))).ReturnsLazily(_ => true);
```

One of the benefits is that it takes advantage of type inference, so you don't need to specify `IFoo` again.

**Comment by blairconrad** [comment]
@joergpichler, late-breaking option that @thomaslevesque thought of today: if switching to use `A<>.That.IsSameAs()` becomes annoying, you could globally disable the "if it enumerates the same, it's equal" behaviour that was turned on in FakeItEasy 8, by using a [custom argument equality comparer](https://fakeiteasy.github.io/docs/8.1.0/custom-argument-equality/) to force comparison via `ReferenceEquals`.
