### ISSUE TITLE
InvokesAsync - possible?

### ISSUE THREAD

**Issue by kristho91** [FakeItEasy/FakeItEasy#2030]
Hi,

Is it possible to do async-stuff in .Invokes()? This compiles fine - but I get a warning: "Avoid using 'async' lambda when delegate type returns 'void'"

```
A.CallTo(() => MyMethodAsync())
    .Invokes(async () => await SomeOtherAsync())
    .ReturnsLazily(() => "Return value"));
```

What is the preferred way to do something like this?

**Comment by thomaslevesque** [comment]
Hi @kristho91,

At the moment there isn't an `InvokesAsync` method, and adding it would be pretty difficult, because the whole FakeItEasy processing pipeline would need to be made asynchronous. So it's not likely that we'll add this anytime soon.

However, you can easily work around this limitation by doing everything in `ReturnsLazily`:
```csharp
A.CallTo(() => MyMethodAsync())
    .Invokes(async () => await SomeOtherAsync())
    .ReturnsLazily(async () =>
    {
        await SomeOtherAsync();
        return "Return Value";
    });
```

`ReturnsLazily` expects a `Func<Task>` here; it doesn't care that it's asynchronous, it will just return the task produced by the async delegate, and your own code can await it.

**Comment by kristho91** [comment]
@thomaslevesque 

Thank you!

Had to do this, though:
```
A.CallTo(() => MyMethodAsync())
    .ReturnsLazily(async x =>
    {
        await SomeOtherAsync();
        return "Return Value";
    });
```

ReturnsLazily expected an input value when using with async. But not when using it without. Maybe a bug?

**Comment by thomaslevesque** [comment]
Oh? Works fine for me:

![image](https://github.com/FakeItEasy/FakeItEasy/assets/1864281/f75cd49c-773d-4470-9450-6e67de0c2926)

What error are you seeing?

**Comment by kristho91** [comment]
My mistake :sweat_smile:
The example needs to be a bit more convoluted to work:

![image](https://github.com/FakeItEasy/FakeItEasy/assets/2781949/17152e0e-fd36-416b-af61-af4ff96f5877)

It works then MyMethodAsync returns Task<MyObject> - but not when it returns Task<IMyObject>
