### ISSUE TITLE
Overhaul project naming

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#280]
My proposal:

![image](https://cloud.githubusercontent.com/assets/677704/2536072/bfbefddc-b598-11e3-83ee-65b3ecc41c5c.png)

Points to note:

* What we are currently calling 'specs' I tend to refer to as 'acceptance tests'. I.e. black box tests written in the language of the public API which ignore all implementation details
* What we are currently calling 'integration tests' are what I tend to refer to as 'component tests'. I.e. semi-white box testing of subsets of the implementation details behind the public API
* Unit test remain as the name for white box testing of individual classes which may or may not form part of the public API
* On disk, all test projects will be moved to a 'tests' subfolder of 'Source' (or 'src' if we agree on #279)
* The framework suffix is mandatory on all projects to avoid ambiguity and the suffixes used match the nuget framework identifiers but using .NET casing rules
* 'FakeItEasy.IntegrationTests.External' is removed and the formatter it contains is moved to 'FakeItEasy.Examples.Net40'. If we choose to implement #281 then we will need to do something else. Perhaps we can keep the project and just rename it to 'FakeItEasy.Tests.Component.External.Net40'.
* The rake tasks `spec` and `integ` would be renamed to `accept` and `component`

Looking forward to hearing any opinions on this.

**Comment by blairconrad** [comment]
Instead of separate projects for the various framework projects, would we ever consider one project (of each type - the production code, unit tests, component tests, acceptance tests) with separate configurations for the frameworks? I know the magic ["include lots of files" trick](https://github.com/xbehave/xbehave.net/blob/011a9b11290a8f21a39dfe4e3b2ae02efed4c7c5/src/Xbehave.Net45/Xbehave.Net45.csproj#L67) can make it easy to include all the code (and all the tests) for the framework-specific projects, but so does multiple configurations, and I thought this might be another option.
It seems to work well enough for Castle.Core, and makes for a smaller/more manageable Solution Tree in the IDE.

**Comment by adamralph** [comment]
IIRC I tried that initially with xbehave but soon went off the idea and switched to separate projects instead. The exact reasoning escapes me however.

I think it might work quite well when you only have progressive versions of the desktop CLR but once you started mixing in Silverlight and Win8 etc. the configs start to diverge a lot and all of a sudden you have to try and move stuff which normally sits outside the 'debug' and 'release' config properties to inside them and things can start to get a bit hairy. 

Ultimately I think it may involve spending a lot more time hacking around in the csproj XML than otherwise and that's something I'd prefer to avoid. If you want to give it a try and show us how it looks then by all means go ahead. Perhaps my fears are unfounded.

**Comment by blairconrad** [comment]
Okay. I wondered if there might be a reason. I see no Win8 in their project, but .NET 3.5 through 4.5, Silverlight 4.0 and 5.0, and Mono 2.6 and 2.8, at least.
I'm in no huge rush to jump into the renaming (it's all about 2.0, and after that, I may need to spend time on other projects), but if the issue is around when things have calmed down, I could give it a go.

**Comment by adamralph** [comment]
I'm not sure if this issue is still valid. We only have one version of each project now. Shall we close this?

I'm still not so happy with the naming of our test projects, but I can spin off a separate issue for that if it bothers me enough.

**Comment by thomaslevesque** [comment]
:+1: to close
