### ISSUE TITLE
Verifying multiple method calls with reference parameters

### ISSUE THREAD

**Issue by cecilphillip** [FakeItEasy/FakeItEasy#306]
There's my scenario. I have a method that gets called twice with an object instance parameter to update it's status in a db. The same instance is used in both cases. I'm trying to verify that it's getting called with the once for each status. The correct number of calls are being caught, but when I inspect the Arguments property for both ICompletedFakeObjectCalls the arguments have the same Status values. Only the last status is preserved.

``` csharp
using(var fake = new AutoFake())
{
    // removed the setup code    
    var input = new StepStarter
    {
        JobId = Guid.NewGuid().ToString("D")
    };

    var domain = fake.Resolve<ParsingFileDomain>();
    domain.ParseFiles(input); //IJobFileRepository.Update gets called here twice

    var x = A.CallTo(() => fake.Resolve<IJobFileRepository>().Update(A<JobFileModel>.That
             .Matches(m => m.Status == JobFileStatus.InProcess))); //i just added this to inspect the properties

    x.MustHaveHappened(); 

    A.CallTo(() => fake.Resolve<IJobFileRepository>().Update(A<JobFileModel>.That
                    .Matches(m => m.Status == JobFileStatus.ParsedFailed)))
                    .MustHaveHappened();
}
```

Is there a better way for me to capture this?

**Comment by blairconrad** [comment]
As @thomaslevesque points out in https://github.com/FakeItEasy/FakeItEasy/issues/965#issuecomment-271941598, this may not be resolvable:

> In order to make your assertion work, FakeItEasy would need to be
> able to check if the argument matched the constraint *at the time of
> the call*, but since the assertion is made *after* the call, there's
> no way to know in advance what the assertions will be. The only way
> make this work would be to clone the arguments of each call when the
> call is recorded, to have a "snapshot" of the arguments against
> which the constraints could be evaluated. But if we did that,
> another very common scenario would no longer work:
>
> ```c#
> A.CallTo(() => repo.Update(user)).MustHaveHappened();
> ```
>
> because the recorded value for the argument would now be a clone of
> the original `user`, so reference comparison would return false.
>
> As far as I can tell, there is no way to make both scenarios work,
> so I think we should support the most common one.

**Comment by cable729** [comment]
I actually think it is possible to make both work. The default way to compare objects is by reference, so this kind of thing already works:

    var user1 = new User();
    var user2 = new User();
    repo.Update(user1);
    repo.Update(user2);
    A.CallTo(() => repo.Update(user1)).MustHaveHappened();
    A.CallTo(() => repo.Update(user2)).MustHaveHappened();

If we want to augment the library to store an accurate representation of each call, we need to store a clone of each object as well as its reference. So the above would work by comparing by reference, and the below would work by comparing by cloned value:

    var user = new User { Id = 5 };
    user.Update(user);
    user.Id = 10;
    A.CallTo(() => repo.Update(A<User>.That.Matches(u => u.Id == 5)))
        .MustHaveHappened(); // currently fails

**Comment by cable729** [comment]
However, I'm not really a fan of asserting like this. Doing complex assertions is painful, because you don't get the nice assertion printout of exactly what matching failed. So either I have to re-run the test and debug it or take out some matching logic one by one. I'd like to do something like this:

    var calls = Get.CallsTo(() => repo.Update(A<User>._));
    calls.First().Arg<User>(0).Id.Should().Be(5);

**Comment by thomaslevesque** [comment]
> we need to store a clone of each object as well as its reference

Yes, I thought about it too, but it raises a number of other issues. For instance:

- how deep should the clone be? If it's a shallow clone, it just moves the problem a bit further without actually removing it. This would still fail because `u.Foo` wouldn't be cloned.
    ```
    A.CallTo(() => repo.Update(A<User>.That.Matches(u => u.Foo.Id == 5)))
        .MustHaveHappened();
    ```

- If it's a deep clone, where do you stop cloning? what about circular references? It's a pretty hard problem... And anyway, not all objects are clonable.

- When do you use reference comparison, and when do you make a clone comparison? What do you do for a constraint like `A<User>.That.Matches(u => u.Equals(user))` (which is actually equivalent to just `user`)?
