### ISSUE TITLE
Faking virtual members before constructor execution

### ISSUE THREAD

**Issue by matkoch** [FakeItEasy/FakeItEasy#365]
In our codebase we need to mock objects, whose constructors contain virtual/abstract member calls. (For us, it is unfortunately not an option to remove this code smell.) Using FIE, there is no way to setup calls to these members, which results either in an exception (MissingMethod) for the abstract member, or an modifiable behavior of the virtual member. We like FIE a lot for it's syntax, but so far this is a problem that we could only solve with converting to Moq. Moq, postpones the creation of the proxy type until `mock.Object` is called. Thus, I can make all the setups in front of the fake type generation/creation.

So far as explanation for my problem. Hope to see some solutions :)

**Comment by blairconrad** [comment]
The changes requested in this issue are covered by the following:

* #368 (fixed in release 1.25.1), which provides better default behaviour for virtual (and abstract) methods called by constructors, and 
* #371 (in progress, as I type), which will allow configuration of virtual methods _before_ they are called by constructors

Accordingly, I'm closing this as a duplicate.
