### ISSUE TITLE
Align use of culture for string formatting

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#399]
Currently there seems to be quite a mix between the usage of `CurrentCulture` and `InvariantCulture` for string formatting throughout the code base. This should be reviewed and aligned where appropriate.

**Comment by jimmyheaddon** [comment]
Correct me if I'm wrong, but generally anything that relates to parsing or formatting strings, numbers or dates/times should use CurrentCulture, whereas anything relating to generating a textual representation of values, or persisting values in a well defined format, should use InvariantCulture.

Interestingly we have a StringExtension.FormatInvariant() method which is used 12 times.  OutputWriterExtensions.Write() is an example where I believe we use InvariantCulture but should be using CurrentCulture, but I'm not familiar with the code base so that might be an incorrect assumption.

See [Using the InvariantCulture Property](https://msdn.microsoft.com/en-us/library/4c5zdc6a(v=vs.100).aspx) and [Using the CurrentCulture Property](https://msdn.microsoft.com/en-us/library/se513yha(v=vs.100).aspx)

**Comment by blairconrad** [comment]
@jimmyheaddon I don't understand the difference between "parsing or formatting strings" and "anything relating to generating a textual representation of values". My general feeling is that InvariantCulture is for computers to read and write with, and CurrentCulture is for humans.
I think you're right about `OutputWriterExtensions.Write`.
(Although I secretly think that for the data that we display, and for the target audience, i.e. developers, the whole point is just a little bit moot. But why be sloppy, and if the point is moot, there's no _harm_ in using the theoretically more proper culture.)

**Comment by adamralph** [comment]
Ultimately I think we need to review every use of each and decide if it's appropriate. It may indeed turn out that everything is OK as is and if so, I'll just have to apologise for wasting people's time :stuck_out_tongue:

**Comment by blairconrad** [comment]
Your comments are never a waste of time. If nothing else, checking will assuage our doubts.

**Comment by blairconrad** [comment]
@adamralph, @thomaslevesque. I can take a look at this. I'll see where we specify culture and see what makes sense.
I'm inclined to prefer current culture unless there's a very clear reason not to (and I don't expect many), partly because it may give the users a better reading experience and so many things default to it (`string.Format`, bling strings, …).

Anyhow, let's see what I find!

**Comment by thomaslevesque** [comment]
@blairconrad pay special attention to usages of string interpolation. By default it uses the current culture.

**Comment by blairconrad** [comment]
Yes. "bling strings".

**Comment by thomaslevesque** [comment]
> Yes. "bling strings".

Ah, yes... didn't realize what you were talking about ;)

**Comment by blairconrad** [comment]
I shouldn't rely on my jargon.

Although I gotta say, I wasn't planning on looking at all the places where we're implicitly using `CurrentCulture`. It'd be easy to find the instances of string interpolation and `string.Format`, but I figure if we're doing this now, and it hasn't been a problem, why not leave it? I'm looking at instances where explicitly specify a culture (whether it be current, invariant, or whatever) and seeing if it makes sense for it to be the current culture.

**Comment by blairconrad** [comment]
And I'll be running _our_ tests under different cultures to make sure we don't introduce any problems for people working on the repo in some non-sensible (read "en-CA") culture.

**Comment by adamralph** [comment]
For the record, the way to create culture invariant strings using bling strings is to use [System.FormattableString.Invariant ](https://msdn.microsoft.com/en-us/library/system.formattablestring.invariant(v=vs.110).aspx), but unfortunately it's only in .NET 4.6 and above.

**Comment by thomaslevesque** [comment]
> For the record, the way to create culture invariant strings using bling strings is to use System.FormattableString.Invariant , but unfortunately it's only in .NET 4.6 and above.

Not really an issue, we can easily add a compatibility shim.

**Comment by blairconrad** [comment]
Sure, but it's all long and stuff. Takes away some of the benefit of the `$`. Also I'm still hoping we don't have any (many) Invariants.

**Comment by blairconrad** [comment]
This issue has been released as part of [FakeItEasy 3.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.1.0).
