### ISSUE TITLE
Adding additional attributes to a fake of an already faked type fails silently

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#437]
Spun off from #436.

``` C#
var constructor = typeof(BarAttribute).GetConstructor(new[] { typeof(string) });

var fake1 = A.Fake<Foo>(x => x.WithAdditionalAttributes(new[] { new CustomAttributeBuilder(constructor, new object[] { "1" }) }));
var fake2 = A.Fake<Foo>(x => x.WithAdditionalAttributes(new[] { new CustomAttributeBuilder(constructor, new object[] { "2" }) }));
var fake3 = A.Fake<Foo>(x => x.WithAdditionalAttributes(new[] { new CustomAttributeBuilder(constructor, new object[] { "3" }) }));

Assert.AreEqual("3", fake3.GetType().GetCustomAttributes(typeof(BarAttribute), true).Cast<BarAttribute>().First().Value);
```

This test will fail because the attribute with the value of "1" is returned although I'd expect it to return the attribute with value "3" (since I'm checking fake3). This is because all fakes are of the same type (Castle.Proxies.FooProxy, DynamicProxyGenAssembly2, DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69) and that type is only created once.

Until a solution to #436 can be found (e.g. each fake has it's own type) we should at least throw an exception when the second fake is created, stating that the type has already been created and therefore additional attributes cannot be added. Nasty, but at least it's owning up and telling the truth, rather than silently failing and leading the test author into forensics to discover why their tests aren't working.

**Comment by adamralph** [comment]
Hold off for now - only required if we can't find a (timely) solution to #436.

**Comment by blairconrad** [comment]
> Hold off for now - only required if we can't find a (timely) solution to #436.

Based on https://github.com/FakeItEasy/FakeItEasy/issues/436#issuecomment-222655976, I don't think we're getting a fix for #436 anytime soon. Do we still see a reason to hold off?
I wouldn't wait just to avoid extra work, and I don't think that introducing the exception and then rolling it out when #436 is breaking, so I think we could keep the minor release train going.

**Comment by adamralph** [comment]
:+1: to go ahead with this now.

**Comment by adamralph** [comment]
Would we consider this a breaking change?

**Comment by blairconrad** [comment]
I wouldn't consider it to be breaking. It already doesn't work. We'd just be telling people now.

**Comment by thomaslevesque** [comment]
> I wouldn't consider it to be breaking. It already doesn't work. We'd just be telling people now.

Agreed

**Comment by blairconrad** [comment]
After looking into this, I'm inclined to **wont-fix**:

1. this is actually a step backwards for our fancy .NET Standard package, which is using a version of Castle.Core that contains the fix that #436 needs
2. if by some chance people are adding attributes (differing, which can even include just one attribute on one fake and none on another) that they don't _require_, their tests will break, with no benefit to them
3. I don't see a reliable way to tell if `CustomAttributeBuilder`s are equivalent - the `Equals` method does reference comparison. The tests that accompany castleproject/Core#78 only examine the behaviour when the same instances of `CustomAttributeBuilder`s are used—that's why they work. Now, for the Castle.Core change, it means that cache of type proxies may grow larger than anticipated and that performance is not what we'd like. But only if types are proxied with additional attributes.
For this issue, if we misclassify `CustomAttributeBuilder`s as being different when they aren't, we'll prevent users from writing valid tests.

It's possible that we could work around #3 by reflecting into the type or some such, but I'd rather not. Especially not for this issue, which is probably not bothering anyone right now (uses of `WithAdditionalAttributes` are nearly non-existent on GitHub) and should go away when Castle.Core goes 4.0 and we pick it up.

**Comment by thomaslevesque** [comment]
I didn't really understand what you were talking about in #3 until I looked at the implementation of https://github.com/castleproject/Core/pull/78. The implementation is indeed flawed, and the tests don't show it because, as you noted, they're flawed as well.

But I don't think it's difficult to tell if two `CustomAttributeBuilder`s are equivalent; it's just a matter of comparing the attribute types, constructor arguments, and property and field values.

**Comment by thomaslevesque** [comment]
> But I don't think it's difficult to tell if two CustomAttributeBuilders are equivalent; it's just a matter of comparing the attribute types, constructor arguments, and property and field values.

Scratch that... I just realized the members of `CustomAttributeBuilder` are not public 😭 

So, as you said, I don't think there's a reliable way to compare two `CustomAttributeBuilder` instances. Because of this, I think https://github.com/castleproject/Core/pull/78 does more harm than good and should probably be reverted.

**Comment by thomaslevesque** [comment]
My PR to fix the custom attribute comparison (https://github.com/castleproject/Core/pull/219) has been merged, so we can now fix the problem by upgrading to Castle.Core 4.0.0-beta002.

However, since there are breaking changes in the API, it means that the code between the stable and netstd versions of FakeItEasy will have to be different until the final release of Castle.Core 4.0.0... Do we want to do it know and pepper the code with `#if`s, or wait until the stable release?

**Comment by blairconrad** [comment]
I think it's better to wait.

**Comment by adamralph** [comment]
Since we are not going to do this in two stages anymore, this issue is redundant. We are fixing the bug #436 in 3.0.
