### ISSUE TITLE
rename `IFakeOptionsBuilder.OnFakeCreated` to `ConfigureFake`

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#454]
Spun off from #371, as a result of https://github.com/FakeItEasy/FakeItEasy/pull/447#issuecomment-72695211. Reflects the fact that the call be made before the fake is created.

**Comment by adamralph** [comment]
I've labelled as an enhancement since there has to be some kind of driver behind making this breaking change. I'm now wondering if it shouldn't just be part of https://github.com/FakeItEasy/FakeItEasy/issues/371. I guess the question is, if we weren't doing #371, would we do this change anyway? Or does it only make sense as part of #371 and indeed, is it necessary to for the API changes in #371 to make sense?

**Comment by adamralph** [comment]
I'm probably over thinking this. Happy to leave as is. And you're right, having this separate communicates things more clearly, which is the most important thing.

**Comment by blairconrad** [comment]
Had we not done #371, we probably wouldn't've renamed.
Still, I like pointing at the change. Let's leave everything as it is.
Good call on the label.

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
