### ISSUE TITLE
remove `Fake<T>` / Unnatural fakes

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#460]
Back when we performed the "clean up types" analysis for #410 and #374, I said that `Fake<T>` was required for the public API, but as I was about to update the [Creating Fakes](https://github.com/FakeItEasy/FakeItEasy/wiki/Creating-Fakes) page I realized that `Fake<T>` is only required to support [Unnatural fakes](https://github.com/FakeItEasy/FakeItEasy/wiki/Creating-Fakes#unnatural-fakes), which mostly seem to exist to provide Moq-style fake creation.

Me, I would be willing to say that, like `Any` and `Configure` (removed in #408), this type has served its purpose and should be removed in favour of the now-standard `A.Fake<T>`. If we're agreed, I think we should add this issue to the 2.0 milestone.

**Comment by adamralph** [comment]
I agree. Let's kill it for 2.0.

**Comment by blairconrad** [comment]
@ploeh, when this issue is fixed, I think AutoFakeItEasy will no longer be compatible with FakeItEasy 2.0.
Given my shallow understanding of AutoFixture, I think it would be best to change the library to use `A.Fake<T>` to create fakes, rather than `new Fake<T>`.
That _should_ keep AutoFakeItEasy compatible with FakeItEasy 1.x and 2.x.
Unless you object, I can make an issue. And possibly work on it, as time allows.

**Comment by ploeh** [comment]
Thanks for the heads-up.

Are you saying that you're going to remove the `Fake<T>` type in the future?

**Comment by blairconrad** [comment]
That is exactly what I'm saying. I'm a rebase away from being able to open a PR.

**Comment by ploeh** [comment]
OK, thanks for your answer.

It most likely *will* break AutoFakeItEasy, but I'm not going to tell you to how to move your library forward.

However, it's beyond me why anyone would want to throw away type information in a statically typed language. Basing an API on static methods and properties instead of objects and types is to make it less reusable, not more.

**Comment by blairconrad** [comment]
@ploeh, I don't follow your comment about throwing away type information and the reusability of the API. I do see value in presenting and maintaining a smaller API, though, and at present see no functional value in keeping the `Fake<T>` type.

Could you expand on your comment for the shallower thinkers among us? Perhaps you see something that I've missed, and we'll reverse our decision on `Fake<T>`.

**Comment by ploeh** [comment]
If I'm not much mistaken `A.Fake<T>` is a static member (actually: *method*, in the version of FakeItEasy I'm currently looking at...) with the return type `T`. This contains less statically available information than `Fake<T>`.

Why? Well, `T` can be any type, but is typically an interface or abstract base class. Given an object of type `T` you have no static type information available to you to tell whether or not it was generated by FakeItEasy.

The FakeItEasy API probably have some way to answer that question, but I can't see how you can answer that question without calling a method or function. Calling a method can fail at run-time.

Now, if you have a `Fake<T>`, you can *statically* identify that this is something else than `T`. There's no reason to call a method to discover that: your code simply doesn't compile if you try to use the one for the other.

This is the way Moq works, although it's called `Mock<T>`. All the configuration (setup/verification) you want to do, you do on `Mock<T>`. As long as you do this on `Mock<T>` it works. If you attempt to configure `T` directly, it *doesn't even compile*.

That's the whole point of a type system: model the API in such a way that illegal states are unrepresentable.

This also means that anyone building higher-level tools on top of a library can pass `Mock<T>` around as separate objects from the `T` objects generated by the `Mock<T>` objects, and the compiler can tell the difference. It's not only for AutoFixture - it's just a much more flexible design in general. It also follows the [Zen of Python](https://www.python.org/dev/peps/pep-0020): *Explicit is better than implicit.*

As a concrete case in point: NSubstitute has always been implemented in the way you propose, whereas Moq has a proper object model. For AutoFixture, we've been able to implement an Auto-Mocking Container based on both libraries, similar to AutoFakeItEasy, but AutoMoq has a much richer feature set than AutoNSubstitute because of these design differences.

When building a higher-level tool, with Moq, I can pass around `Mock<T>`, and it's immediately clear that this is something that represents a Test Double. The compiler protects me from doing something stupid.

With NSubstitute, I can only pass around values of type `T`, which means that in *every method* that receives `T` as input, I need to do some sort of run-time check to figure out if the `T` value was generated by NSubstitute. This leads to much more brittle code that fails at run-time.

Since, in AutoFixture, we've already been able to deal with this sort of design for NSubstitute, we can probably also do it for FakeItEasy, but the implementation may be less feature-rich, and more bug-ridden as a result.

Further reading (in F#, but to some extent applicable also to C#):

- http://fsharpforfunandprofit.com/posts/designing-with-types-making-illegal-states-unrepresentable
- http://tomasp.net/blog/2015/library-frameworks/index.html

**Comment by blairconrad** [comment]
Thanks for the detailed expansion. I'd've responded earlier, but work and appointments interfered. Also, the linked articles were not short!

You are, of course, right about how `new Fake<T>` and `A.Fake<T>` work. And I see how there are advantages in having a `Fake<T>` and knowing that this is the item that allows one to configure and obtain a test double. I'm a fan of letting the compiler help me fall into the pit of success.

That being said, as I understand it, the `A.Fake<T>` construction has been with FakeItEasy since the beginning of time, and aligns with the "(nearly) anything you do with FakeItEasy you do by starting with `A.`" philosophy. It's been the blessed way to create the fakes for quite a while now, and I wouldn't want to start pushing users in the other direction. And certainly not get rid of that mechanism for creating fakes!

I've seen a number of comments about this being one of the reasons those who prefer FakeItEasy over Moq (for example) do—no need to type `.Object` to be able to give your test doubles to the SUT. So up 'til now I'd been thinking of the `Fake<T>` usage as a solely stylistic choice, with no technical merit. And maybe [something to help lure in the Moq users](https://github.com/FakeItEasy/FakeItEasy/wiki/Creating-Fakes#unnatural-fakes).
I appreciate being shown the technical value in `Fake<T>`, at least to the end users who wish to have the static identification of the types.

Now, I'm not saying that the static identification is of no use to the framework developers such as yourself, just that my primary concern is the end users. If nothing else, I'd expect the framework developers not to run into confusion over whether an object is a configurable test double, unless they're being passed around, but even then I'm not convinced there's a need. Why you'd create a fake (of whatever ilk) and then pass it around for a bit and then possibly decide to configure it, I don't know. The vastly more common case would seem to me to be create the fake, configure it if need be, and then pass it around.

> With NSubstitute, I can only pass around values of type T, which means that in every method that receives T as input, I need to do some sort of run-time check to figure out if the T value was generated by NSubstitute. This leads to much more brittle code that fails at run-time.

I think there are few cases where you'd need to know whether `T` is a configurable fake or not and where using `Mock` or `Fake<T>` help, but I'm happy to be proved wrong.

I took a peek at AutoMoq, and see that `Mock` is used to provide some extra value, but in many cases it seems an `object` is passed into a method, which then does a safe cast to `Mock` and bails if the result is null. (`MockConfigurator<T>` is one exception, but it's used directly after creating the double, so there would at least not be any confusion.) The rest of the code in the method can work with the security afforded by the type system, but you do have to perform the soft cast. In practice, this seems little different from (for example) asking FakeItEasy if the passed-in object is a fake and then proceeding to configure it if it is.

I'm not trying to discount the value of having the proper type system, nor to be fractious just for the sake of it. I appreciate your input. I am learning. And I'm definitely wavering in my position.
I'm just trying to determine how much benefit is really gained _in this case_ by providing the typed "test double holders" relative the cost of providing the clients with two ways to produce the test doubles.

**Comment by blairconrad** [comment]
I'm back. I've thought about @ploeh's comments and the usefulness of being able to lean on the type system to prevent errors earlier than runtime.
It feels good, like not requiring newly-constructed objects to be "initialized" before use. Truth be told, I think it's a system that I'd _want_ to use.

Given FakeItEasy's "everything starts with `A`" position, I probably wouldn't _add_ `new Fake<T>` to the API, and I probably won't even switch away from using it, given the difference in syntax between configuration and verification.

But now that I realize it's not just a stylistic choice, I think we should keep it. Or at the very least, I'm not in a rush to remove it. Someone may be benefiting. And if it helps the framework builders as @ploeh says, then why not support them?

@adamralph, how do you feel about going along with my newfound position? I'm thinking of closing this issue without a code change?

**Comment by ploeh** [comment]
Regardless of what you ultimately decide, I'd like to commend you for giving this serious thought. Not many people want to *actually* listen, but you've already proven that you do that, and for that you have my respect. :thumbsup:

---

Another way to look at this issue is that your design principle that *everything starts with `A`* is your Domain-Specific Language (DSL). A common insight shared among many people designing DSLs is that the DSL shouldn't be the object model; rather, the DSL is used to populate a [Semantic Model](http://martinfowler.com/dslCatalog/semanticModel.html). In the case of FakeItEasy, I would say that the `A.Whaterver` is your DSL, and the `Fake<T>` is your Semantic Model.

This is a battle-proven design. A concrete example that I know of is AutoFixture, which itself uses this architecture (with and without FakeItEasy). It has served us well for more than 5 years now.

**Comment by adamralph** [comment]
@ploeh @blairconrad thanks for the informed opinions. Given there seems to be clear benefit in `Fake<T>`, perhaps not for test authors but certainly for integration package owners, I'm leaning towards keeping it. I'd be happy to close this as a wontfix.

As an aside, we should take some of the popular integration packages, at a minimum AutoFixture.AutoFakeItEasy, Machine.Fakes.FakeItEasy and Autofac.Extras.FakeItEasy and attempt to upgrade their source to the latest 2.0 beta to assess impact.

**Comment by blairconrad** [comment]
Leaving `Fake<T>` for now. Perhaps for good.

**Comment by blairconrad** [comment]
@ploeh, perhaps this isn't the best forum for this conversation, but parts my interest some.
First, thanks for your kind words. We do try to be take things seriously and consider the impact of our actions on our clients and collaborators. We'd be silly not to consider your well-reasoned suggestions.

Regarding the role of `Fake<T>`, I'm not entirely sure it's our Semantic Model. It really only exists to provide a different syntax for the configuration of the fakes. I fear that it's playing the role of a DSL just as the `A.` methods are. Removing it really doesn't affect any other aspect of FakeItEasy.

Of course, I may just be misinterpreting "Semantic Model", and perhaps `Fake<T>` is one. Given that we're going to be keeping it for a while longer (at least), it's perhaps not such a big deal. I just wanted to clarify; `Fake<T>` is nearly content-free.

**Comment by ploeh** [comment]
@blairconrad Thanks for clarifying. It may be that I simply misinterpreted the role of `Fake<T>`, not being too familiar with the FakeItEasy code base.

However, it *looks* like a prime candidate for a Semantic Model.

Moq, that I'm more familiar with, uses `Mock<T>` for its API, and while it doesn't have a built-in DSL, I'd guess that it wouldn't be too hard to define an internal DSL on top of it if you'd want to. That's the power of that model.
