### ISSUE TITLE
Documentation page on Assertation could use some mention of scope

### ISSUE THREAD

**Issue by RichardLangFromNZ** [FakeItEasy/FakeItEasy#518]
https://github.com/FakeItEasy/FakeItEasy/wiki/Assertion

I'm using FakeItEasy 1.25.3 with NUnit 2.6.4 for testing c# code.  With no concept or awareness of the testing framework (if any) it is being used within, by default FakeItEasy works with a single common scope for the entire execution of a test suite, and MustHaveHappened()/ MustNotHaveHappened() will report usage for the entire suite execution to date, rather than for a specific test case.  To limit MustHaveHappened()/MustNotHaveHappened() reporting to a specific test case, which I'd consider to be the usual use-case, I had to instantiate and activate a new FakeScope with the Fake.CreateScope() call in the test setup routine, then dispose of it again in the teardown routine.  

Simple enough, however I had to figure this out for myself. As I'd consider this to be the usual use-case for the MustHaveHappened()/ MustNotHaveHappened() assertations, I recon this warrants a mention in the documentation (at present the only mention of FakeScope and CreateScope is within the more esoteric OrderedAssertation documentation (https://github.com/FakeItEasy/FakeItEasy/wiki/Ordered-assertions))

**Comment by blairconrad** [comment]
Thanks, @RichardLangFromNZ. It's true that `FakeScope` is not well documented. In fact, I think a large number of people don't know about it at all.

I know very little about it myself and have, in about 2 years of FakeItEasy use, never created a `FakeScope` except in one case where I was converting an old test at my day job from using a different mocking framework to FakeItEasy. The test cared about the order of some operations, and so I used an `OrderedAssertion`, as you say.

I'm curious about your workflow, and would like to learn a little more about it in order to see what's giving you problems and how we can best help.
You didn't say, but my guess is that you're creating a fake and then using it for multiple tests? In that case, the record of which calls have happened would naturally carry over from one test to another.
Of course, I may be completely off base, and something else is happening.

Can you describe or provide examples of a typical use case or test suite? That may help us understand your difficulties and help find a way that would work better for you.

**Comment by RichardLangFromNZ** [comment]
Good point, I could/should rebuild my fake in the setup of each individual
test, rather than carrying it over.  Don't know why I didn't twig to that
in the first place.

thx

Richard.

**Comment by blairconrad** [comment]
No worries. Sometimes it's easy to think of the fakes as special and shove it in the fixture setup or make it static or something.

You did bring up a good point about the lack of scope documentation. It's something that's been on my mind for a while, but I don't really understand them that well, think they're kind of an edge feature, and worry about their thread-safety (I think there isn't any), so I've been holding off writing anything up.

**Comment by blairconrad** [comment]
@RichardLangFromNZ Oh, while I'm here, welcome to GitHub!
From the look of things, you signed up just so you could make this issue. Thanks for caring!

**Comment by blairconrad** [comment]
@RichardLangFromNZ, you sound happy, so I'll close this issue (I made a more general "document FakeScope" issue as #519).
If you're not happy, please reopen and we'll see what we can do.
