### ISSUE TITLE
Rename `IFakeOptionsBuilder` to `IFakeOptions`

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#520]
Extracted from https://github.com/FakeItEasy/FakeItEasy/issues/461#issuecomment-118212168, since

1. I think it's a good move anyhow, and 
2. If we do this, it'll affect #461, and may simplify our discussion of that issue

----

The more I look at things, the more I think that what users see as "fake options builders" could really just be "fake options" to them. That would alleviate _some_ of the naming pressure (for the API) in #461, not just in the discoverable interface we're talking about there, but when using `A.Fake<T>(Action<IFakeOptionsBuilder<T>>)` too.

If we made the change, the internal `FakeOptions` would collide with the class we'd use to implement the public `IFakeOptions`.
We could:

1. rename `FakeOptions` to something like `FakeCreationOptions`, or
2. collapse `FakeOptionsBuilder` and `FakeOptions`, as I'm not sure the latter is pulling its weight). If we did this we _could_ still implement two interfaces, to separate the "build up the options" actions from the "just get me the data so I can make a proxy" operations.

**Comment by blairconrad** [comment]
I know when I first started using the `A.Fake<T>(Action<IFakeOptionsBuilder<T>>)` method, I found it a little confusing:

>I want to set the fake's options. Oh. There's an options builder. But I don't supply that, I supply an action that _acts_ on a builder.

That kind of thing. At least the interface is fluent, so it's fairly easy to get where you're going once you get started.

**Comment by adamralph** [comment]
Sounds fine to me. We'd definitely have to get rid of `FakeOptions`, not least because ∃ `FakeOptionsBuilder<T>.Options` and we certainly wouldn't want that to become `FakeOptions<T>.Options`.

We'd also need to rename `IFakeOptionsBuilderForWrappers<T>` to `IFakeOptionsForWrappers<T>`. 

I'm also wondering we have this as a separate interface. There is only one implementation of `IFakeOptionsBuilder<T>` and that is `FakeOptionsBuilder<T>`, which also implements `IFakeOptionsBuilderForWrappers<T>`.

Could `IFakeOptionsBuilderForWrappers<T>` be folded into `IFakeOptionsBuilder<T>`? Or does it still need to exist because `IFakeOptionsBuilderForWrappers<T>.RecordedBy()` needs to return a `IFakeOptionsBuilder<T>` and not a `IFakeOptionsBuilderForWrappers<T>`?

**Comment by blairconrad** [comment]
> We'd definitely have to get rid of `FakeOptions`

Agreed.

> We'd also need to rename `IFakeOptionsBuilderForWrappers<T>` to `IFakeOptionsForWrappers<T>`.

Already done!

> I'm also wondering we have this as a separate interface.

I don't mind getting rid of an interface of two, but it may be tricky. You have the gist of it—for the fluent interface to work, we only want to expose `RecordedBy` when the previous method call on the options object is `Wrapping`, so I'd say we need to keep `IFakeOptionsForWrappers<T>`, and `FakeOptions<T>` can explicitly implement it.
Alternatively, we could change the whole `Wrapping`/`RecordedBy` approach, but let me play a bit first. I'll see if I can get everything else changed, and we can take a look at the shape of thigns.

**Comment by thomaslevesque** [comment]
> The more I look at things, the more I think that what users see as "fake options builders" could really just be "fake options" to them.

I totally agree; it's something that used to confuse me when I started using FIE.

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
