### ISSUE TITLE
Switch from NUnit to xUnit.net

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#545]
Now that the specs have switched from mspec to xBehave.net, it probably makes sense to convert the rest of the tests from NUnit to xUnit.net so that we're using a single underlying test framework for all. Given that xUnit.net also has .NET core support in the works, it would also ease the passage to solving #531.

Note that this may also solve #231.

**Comment by blairconrad** [comment]
I'm not sure what "solve da097217cf6bd2470442314cfab6ac2cb34e2f2a" means. That's a commit.

**Comment by blairconrad** [comment]
Also,  how do you feel about holding off on this until after 2.0? :grinning:

**Comment by adamralph** [comment]
Oops! I meant to say "solve #231". Fixed.

No urgency around this at all. Can definitely wait until after 2.0.

**Comment by adamralph** [comment]
Note that this can be done bit by bit, a PR for a test here, another PR for a test there, etc.

One thing that will be required before converting the first test from NUnit to xUnit.net is the introduction of a second pass at executing each test DLL in the rakefile, using the xUnit.net console. I.e. each test DLL will need two passes, one with NUnit console and one with xUnit.net console.

**Comment by mat-mcloughlin** [comment]
That sounds fine to me. Happy to pick up the rake file, also happy to start shifting some across If you like.

Also would you want to move to using fluent assertions as well?

**Comment by adamralph** [comment]
@mat-mcloughlin that would be awesome.

Yeah, for each test you touch, you may as well switch to FA too, that's generally been our policy. Thanks!

**Comment by mat-mcloughlin** [comment]
np, I feel the need to pick up something as this to payback for the fact I haven't contributed to an OSS in months :D

**Comment by blairconrad** [comment]
In order to head off PR comments from the future, how do we feel about having 2 commits per changed file: one for the NUnit Asserts→FluentAssertions (if necessary, many won't be), and one for NUnit→xUnit conversion? It may make things a little easier to read.

**Comment by adamralph** [comment]
:+1: to separating the commits

**Comment by blairconrad** [comment]
@mat-mcloughlin, I'm inclined to remove the **up-for-grabs** label and mark it as **taken** by you.
Suits?

**Comment by mat-mcloughlin** [comment]
sure. planning to start hitting some of theme tomorrow morning

**Comment by blairconrad** [comment]
Thanks, sir!

**Comment by mat-mcloughlin** [comment]
Started moving over to fluent. I'll break it into two separate commits as you say. One for moving to fluent and one for moving to xunit.

Want me to set up a PR now or leave it until complete?

https://github.com/mat-mcloughlin/FakeItEasy/commit/9c74353de6047f35f876174c4cc225a75bf6949f

**Comment by mat-mcloughlin** [comment]
You have a lot of tests :)

**Comment by blairconrad** [comment]
@mat-mcloughlin, thanks for the work!
I've made some early bonus comments on your commit (perhaps premature, your xUnit changes were probably not headed for the PR anyhow), in case you're interested.

Regarding the PR, whatever's easiest for you. If you don't care either way, why not set it up? If you push or repush to the branch, I can take a look as things spill in. It may help streamline the procedure. But if you would rather wait, that's fine too!

> You have a lot of tests :)

Indeed! It's one of the bonuses of working on a library intended to help write tests. We get contributors that like tests. :stuck_out_tongue_winking_eye:

**Comment by mat-mcloughlin** [comment]
thanks for the comment, I'll set up the PR.

Yeah the xunit changes snook in there, I was going to remove them before it got to the PR :). Regarding that though, `v2.1` requires `dotnet4.5` and the project is currently at `dotnet4.0` afaik

**Comment by blairconrad** [comment]
@mat-mcloughlin you're right about `dotnet4.0` of course. My initial reaction was "switch it to 4.5".

But that's going to be tricky for the .Net 3.5 tests, which will pull in two copies of `Tuple` and `Zip`.
Also, there's a ripple effect when changing the Tests project to 4.5: many of the other projects depend on it, such as the examples and integration tests.
We could explore untangling the projects (mostly they just rely on helper code we shoved in the Tests project). Hmm.

To my mind, using two copies of xUnit reduces the advantages of switching away from NUnit.
I can try further chase the ramifications of switching the tests to target 4.5, unless someone has a brighter idea.

**Comment by blairconrad** [comment]
It seems to me that all the test projects could be switched to 4.5, save the .NET 3.5 one.

I'm not sure what to do about the duplicate `System.Tuple` for that one. The warning could be suppressed, but the compiler is choosing the version from mscorlib (4.5), so there's not really any help there.

Options that I can think of:

1. use older xUnit (or even keep NUnit) for the 3.5 tests, as @mat-mcloughlin had suggested
2. remove the tests. There aren't many, and they're of limited value, really
3. rename our 3.5 `Tuple` (and `Zip`?) and use horrible #ifdefs and whatnot to provide it to the 3.5 build, but not others
4. just rename out `Tuple` (and `Zip`?) so we always use our own
5. remove the 3.5 build altogether

I'm not enamoured of any of these, but leave them here for perusal. Maybe some of you smart folks'll come up with something. Or future me…

**Comment by adamralph** [comment]
Could we also upgrade `FakeItEasy.Net35.Tests` to .NET 4.5 and somehow force it to use the shims in `FakeItEasy.Net35` instead of the types in mscorlib?

**Comment by blairconrad** [comment]
Yes, that was my first thought. I can't figure out how, other than to rename (or renamespace). Closest I've come is suppressing the warning and letting the compiler pick the wrong ones.

In case it helps, the warning is 

```
error CS1685 : Warning as error : The predefined type 'System.Tuple' is defined in multiple assemblies in the global alias; using definition from 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll'
```

I've tried referencing System.Core using a different alias, but it made no difference. I'm probably not doing that right.
I'll keep looking.

**Comment by blairconrad** [comment]
I think moving the shims to a different namespace is the approach most likely to work. See a very rough attempt in #564.

**Comment by mat-mcloughlin** [comment]
A bit out of my understand of FIE with this. So I'll just move the assertions over and wait for you guys to decide on what you want to do

That ok?

**Comment by blairconrad** [comment]
> A bit out of my understand of FIE with this.

Maybe me too! Really, it's not so much FIE-ish, as it is Framework-Shimmy. But still not something I do on a daily basis.

>  So I'll just move the assertions over and wait for you guys to decide on what you want to do

@mat-mcloughlin, that would be fantastic. It's valuable work and shouldn't affect or be affected by the change in project target with luck, we'll have it sorted and will be able to upgrade the projects when you're done that phase. Then if you'd like, you can keep going with the NUnit conversion.

**Comment by blairconrad** [comment]
@mat-mcloughlin, I think #568 removed the last barrier to using xUnit 2.0 in all the test projects. If you find any problems, please give me a hoot.

**Comment by mat-mcloughlin** [comment]
will do. Sorry I stepped away from this. Holidays and what have you got in the way :)

**Comment by blairconrad** [comment]
Please, no apologies necessary. You should spend time on things that are important to you. FakeItEasy (and projects of its ilk) are at best a hobby.
We're happy to have your help, and there's no timeline!

**Comment by jeremymeng** [comment]
How is this work going?  I am trying to add a Dnx test project for the #531. However I need either xUnit, or NUnit v3. I had an attempt to upgrade NUnit to v3: (https://github.com/FakeItEasy/FakeItEasy/compare/master...jeremymeng:nunit3) but it makes little sense if we can have xUnit soon.

**Comment by blairconrad** [comment]
@jeremymeng, thanks for asking, and for your work on #531.  
I suspect that @mat-mcloughlin has been pulled away by more pressing matters. In any event, I wouldn't want to try to merge changes to use xUnit before we release 2.0, but if @mat-mcloughlin is unable or unwilling to work on this issue for inclusion shortly after we release 2.0, I'd be content to take it over.

**Comment by jeremymeng** [comment]
@blairconrad Thanks for the update!  Do you have a schedule for v2.0?  Anyway I don't want to wait for xUnit conversion for testing the .NET Core porting changes, so I added a test project based on NUnit v3. I am currently going through test failures.

**Comment by blairconrad** [comment]
2.0.0-rc1 is out _right now_, and I am anticipating that it will be 2.0.0 (except for one "move the docs to read the docs" issue I'm working on), so maybe a week or two? That's kind of a guess. And I'm loathe to make the guess, because that sort of thing tends to attract the forces of chaos and will almost guarantee that we'll not release for a year.

Thanks for your efforts!

**Comment by blairconrad** [comment]
@mat-mcloughlin seems to be unavailable right now, so I'm taking a crack at this, in order to make xUnit tests available for the .NET Core work in as timely a fashion as we can manage.
Sorry, @mat-mcloughlin. We all know that working on OSS is a hobby and this does not in any way reflect badly on you. Please don't be cross with me.

**Comment by blairconrad** [comment]
https://github.com/blairconrad/FakeItEasy/tree/xunit contains my work. So far, I've switched all but one assertion to use FluentAssertions instead of NUnit.
Next steps are to convert `NullGuardedConstraint` and then switch the runner to xUnit.

@FakeItEasy/owners, @jeremymeng, how do we want to proceed for a PR? Should we put this in master before the 2.0 release (I'd been hoping for no more changes, except for #637)? Alternatively we could either wait or make the changes available to the coreclr branch early.

**Comment by adamralph** [comment]
I think this can happen concurrently with 2.0. Whether it gets into `master` before or after 2.0 doesn't really matter. However, I think 2.0 should be our priority.

**Comment by blairconrad** [comment]
Oh, it's my priority. I was just holding off while people commented on #637. I heard a rumour that [there's going to be a ground-breaking revelation](https://gitter.im/FakeItEasy/FakeItEasy?at=56fd1b5dbbffcc665faae2c3) in that area.

**Comment by adamralph** [comment]
LOL - I'm actually writing my comment right now. Don't get your hopes up though... :wink:

**Comment by mat-mcloughlin** [comment]
@blairconrad I'm not cross :)

Things just keep getting in the way. New job (with Adam actually) and now my first kid :/

Again apologies

**Comment by blairconrad** [comment]
@mat-mcloughlin no apologies necessary. I completely understand. Working on FakeItEasy is (at best) a hobby. You're under no obligation. Enjoy your time with your child.

**Comment by blairconrad** [comment]
With #659 and #661 merged, we're getting closer!

**Comment by blairconrad** [comment]
@mat-mcloughlin, how are things going? Do you anticipate returning to this work at some time? If so, I'll assign the issue to you. If not, I'll... remove in-progress, I guess. If you're not sure, we can assign it to you anyhow! It's easy to unassign later.

**Comment by blairconrad** [comment]
Oh! It's already assigned to me. I had forgotten.

**Comment by blairconrad** [comment]
@FakeItEasy/owners, I'm well along in the conversion procedure. There are a few little things that I'd still like to look into. However there are 2 larger stumbling blocks I'd like your input on

1. The albacore XUnitTestRunner behaves a little badly when we ask it to test multiple assemblies, in that it executes the xunit runner once per assembly. This means all the tests that we want to run do get run, but the XML output from the last assembly trumps the previous run. This would be a problem for the unit and integration tests, each of which have two assemblies. Options, as I see them:
    1. split `unit_tests` and `integration_tests` and run the `XUnitTestRunner` twice each
    1. drop `XUnitTestRunner` and just construct an xunit console runner command ourselves

  I'd probably drop XUnitTestRunner, but am happy with either option, or something else, if you've an opinion.

2. The main unit tests at least do not pass when run concurrently. There's an obvious cause in the tests themselves, as many of them replace the current `ServiceLocator` (often by extending `ConfigurableServiceLocatorTestBase`) for the duration of their run. This can have obvious bad consequences when the groups of tests are run concurrently. I'm inclined to delay thinking about that and just serialize the tests (as they have been under NUnit) and, if we're interested, we could make another issue to investigate the making the tests concurrency-safe. Objections?

**Comment by thomaslevesque** [comment]
1. I'm not sure I understand what you mean in option _i_... can't we just output the test results in a different XML file for each assembly?

2. No objection from me. The immediate goal is to switch to XUnit, not to fix the concurrency issues in the tests (of course, we'll have to look into it later, otherwise we lose one of the biggest benefits of XUnit)

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque.

Glad you feel the same way on concurrency.

For the other point, I was just trying to convey that in order to output the test results in a different XML file for each assembly, we'll need to split up the `unit_tests` list (and `integration_tests`) either manually into two variables and run the `XUnitTestRunner` on each in turn, or have each of our tasks iterate over the current list and run the `XUnitTestRunner` on each element in turn, while inferring an appropriate output file name from the test assembly, probably something like `FakeItEasy.Tests.xml` and `FakeItEasy.Analyzer.Tests.xml`, which aren't terrible, but do break with our current pattern of naming the output files according to the build stage (task) rather than the assembly being tested.

**Comment by thomaslevesque** [comment]
OK, so it looks like it's a bug in Albacore, and probably an easy one one to fix... except that [[it was already "fixed" to pass only one assembly to xunit.console](https://github.com/derickbailey/Albacore/issues/47). It was back in 2010, and now xunit.console accepts multiple assemblies... perhaps the "fix" should be reverted.

**Comment by blairconrad** [comment]
Of course, that flavour of albacore has been deprecated in favour of https://github.com/Albacore/albacore, which has moved on quite a bit. Just picking it up will not work, as there are some incompatibilities (and I don't know if it's worthwhile working around them while we're planning on dropping rake at some time).
The test runner in new albacore [has the same behaviour](https://github.com/Albacore/albacore/blob/c7f3e385a2507ef46302e96ca4e4774bcb3136f4/lib/albacore/task_types/test_runner.rb#L105), where the test files (assemblies) are run in sequence, rather than all being passed to the test runner.

We could raise an issue, but for some frameworks, this might be considered a feature. I guess it could be implemented via a new configuration option to control whether the files are passed to the runner one by one or _en masse_.

While I think having the option is the right thing for albacore, I'm not convinced that going down this path is the right thing for FakeItEasy. :wink:

**Comment by blairconrad** [comment]
For what it's worth, I raised Albacore/albacore#207 anyhow.

**Comment by adamralph** [comment]
> have each of our tasks iterate over the current list and run the XUnitTestRunner on each element in turn, while inferring an appropriate output file name from the test assembly, probably something like FakeItEasy.Tests.xml and FakeItEasy.Analyzer.Tests.xml

That's how I do it in xbehave - https://github.com/xbehave/xbehave.net/blob/ed11fcdda746edb9a111ac1b109d4d37f13a7c2a/rakefile.rb#L103-L111

**Comment by blairconrad** [comment]
@adamralph:

> That's how I do it in xbehave

If that isn't an endorsement, I don't know what is. I'll crib.
