### ISSUE TITLE
Provide an external XML annotations file to prevent ReSharper's "implicit captures" warning

### ISSUE THREAD

**Issue by hmemcpy** [FakeItEasy/FakeItEasy#56]
Please see this blog post: http://www.hmemcpy.com/blog/2013/02/preventing-resharpers-implicitly-captured-closure-warning-in-fakeiteasy-unit-tests/

ReSharper will complain about the `A.CallTo` methods, that they implicitly capture local variables. It's possible to prevent this, by teaching ReSharper (via external annotations, so it's completely seamless non-intrusive) that the lambdas are executed immediately by FakeItEasy.

By supplying an external annotations XML together with the DLL, this will "just work", and no code changes required anywhere.

**Comment by adamralph** [comment]
Given that we now have licenses, I'm happy to pay back some of that love by including an annotations file :wink:

**Comment by thomaslevesque** [comment]
> Given that we now have licenses, I'm happy to pay back some of that love by including an annotations file :wink:

If I can make a suggestion: it's *much* easier to add the annotations directly in code than to put them in an external annotation file. The XML syntax is quite verbose, whereas putting attributes in code only takes a few keystrokes (in some cases R# can even do it automatically).

If you're worried about exposing the annotations, you can make them internal, it will still work; that's what I do in my own libraries. BTW, @citizenmatt, I really think they should be internal by default; at the very least, there should be an option to make them internal when copying the default implementation (see [this issue](https://youtrack.jetbrains.com/issue/RSRP-419373) on YouTrack), because it's definitely not something libraries should expose.

**Comment by adamralph** [comment]
@thomaslevesque that sound good to me. I've seen those annotations in some of the dotnet codebases.

If you're interested in contributing than we'd more than happy to accept a PR for this.

**Comment by citizenmatt** [comment]
Yeah, I agree about them being internal by default. We have a few different ways of working with annotations, and none of them are "just right", IMHO. I'd love to see this cleaned up.

Writing XML annotation files is a complete PITA (and not just because it's XML), so I think you'd be best to put them directly in source, if you can. They're not compiled in by default, thanks to the `Conditional` attribute, so you need to define `JETBRAINS_ANNOTATIONS` to get them compiled into the resulting assembly. 

And yes, as an assembly that's going to be used as a 3rd party assembly, making them internal before compiling is (IMO) the best solution.

There is another option, but I wouldn't recommend it over the above. We have an [internal mode](https://www.jetbrains.com/resharper/devguide/Intro/InternalMode.html) menu option that can dump annotations applied in source to an external annotations file. This means you can keep the annotations as public, even reference them through the `JetBrains.Annotations` nuget package, and as long as you don't have `JETBRAINS_ANNOTATIONS` defined, they don't get compiled into the resulting assembly. BUT, you have to manually run this xml generation step each time you do a release, and also add `FakeItEasy.ExternalAnnotations.xml` to your nuget. Not ideal...

**Comment by hmemcpy** [comment]
Heh, I didn't realize this ticket was still active.
I'm all for adding the annotations directly in the source code. I know, for example, Entity Framework uses annotations [directly, e.g. ](https://github.com/aspnet/EntityFramework/blob/bbc1e1843bf3473c39958d65ff565b25be3e36d9/src/EntityFramework.Relational/Metadata/IRelationalPropertyExtensions.cs)

If nobody takes it, I might :)

**Comment by adamralph** [comment]
Ah yes, EF was the one where I'd seen it.

@hmemcpy you''re more than welcome to take it on. If the attributes are internal then I see no downside to including them.

**Comment by hmemcpy** [comment]
Does this mean I can "enhance" your other libraries as well? :P

**Comment by adamralph** [comment]
:grin: I've opened up the floodgates.. OK, go on then... :smile:

**Comment by hmemcpy** [comment]
Hah, I must admit I forgot what was the original intention of this...
Alright, I'll stop spamming and send a PR.

**Comment by thomaslevesque** [comment]
@hmemcpy, are you still working on this?

I just found a bad unit test in my code where I had written `A.CallTo(...)` and forgotten to call `MustHaveHappened()` on it; this caused the test to pass even though it should have failed. Adding the `[Pure]` attribute on the `CallTo` method would prevent this kind of mistake. (technically, it's not really pure, since it mutates the state of the fake manager, but calling `CallTo` and doing nothing with the result it is clearly a mistake.)

**Comment by hmemcpy** [comment]
@thomaslevesque sorry, I've been so busy lately (being a new dad :P) that this completely escaped my mind.
Also, I hadn't considered using `[Pure]` at all, which is a great suggestion!
In fact, now I'm thinking it could be a cure for incomplete chaining of all fluent interfaces!

Let me dust off what I had, and I'll send a PR.

**Comment by hmemcpy** [comment]
Just to make sure, is the desired solution then adding an `Annotations.cs` to the codebase with `internal` visibility?

**Comment by thomaslevesque** [comment]
> Just to make sure, is the desired solution then adding an Annotations.cs to the codebase with internal visibility?

I think it is, @adamralph seemed to agree with the idea

**Comment by hmemcpy** [comment]
@thomaslevesque awesome, that's what I'm doing.

Other than `A.CallTo`, are there other methods that take in a lambda? Except `.Fake<>`?

**Comment by hmemcpy** [comment]
After some thought, and a chat on gitter about this situation, I came to the realization that Annotations are not the best way to solve this.
Initially (2 years ago, in fact), this issue was open to provide a "solution" to ReSharper's "implicit capture" warnings. It's been 2 years, there have been 0 complaints about this.

As for the other thing, the `[Pure]` annotation is not the best solution for this. It does work, but it sends the wrong message ("Value of a pure method is not used") -- without the ability to customize this message (which there is none, [currently](https://youtrack.jetbrains.com/issue/RSRP-438115)), it is saying the wrong thing, as the `A` methods are not pure by definition.
In addition, this causes a bit of a disruption in my own workflow: I use the (excellent) [Postfix Templates](https://github.com/controlflow/resharper-postfix) plugin, and I almost never start with the variable, I type the expression first (e.g. `A.Fake<IFoo>()`), and only then assign it to a variable. If it's annotated with `[Pure]`, then for a brief moment I get a blue squiggly, and this is annoying.

So after 2 years I am going to close my own issue. The "implicit capture" warning has been subdued to a mere hint in R# 9, and in 2 years nobody cared. As for the other (valid) concern of using the fluent API properly - this is *exactly* the kind of thing Roslyn was created for. I believe it would be best to create a Roslyn diagnostic and ship it as a nuget package (maybe include it in FIE itself). This would make those suggestions ReSharper-independent, and is a better fit.

**Comment by thomaslevesque** [comment]
> As for the other thing, the [Pure] annotation is not the best solution for this. It does work, but it sends the wrong message ("Value of a pure method is not used") -- without the ability to customize this message (which there is none, currently), it is saying the wrong thing, as the A methods are not pure by definition.

I agree that using the [Pure] annotation here would be misleading, but right now there is no better one. Hopefully your suggestion on JetBrains' Youtrack will be accepted ;)

> In addition, this causes a bit of a disruption in my own workflow: I use the (excellent) Postfix Templates plugin, and I almost never start with the variable, I type the expression first (e.g. A.Fake<IFoo>()), and only then assign it to a variable. If it's annotated with [Pure], then for a brief moment I get a blue squiggly, and this is annoying.

I understand how it can be annoying to you, but I don't think this plugin is very widely used... so I don't think it's a valid reason not to do it.

> So after 2 years I am going to close my own issue. The "implicit capture" warning has been subdued to a mere hint in R# 9, and in 2 years nobody cared. As for the other (valid) concern of using the fluent API properly - this is exactly the kind of thing Roslyn was created for. I believe it would be best to create a Roslyn diagnostic and ship it as a nuget package (maybe include it in FIE itself). This would make those suggestions ReSharper-independent, and is a better fit.

Perhaps, but right now Roslyn analyzers are only available in VS2015, which hasn't been released yet, and won't be widely adopted in software companies before some time. Also, writing a Roslyn analyzer is much harder work than annotating a method with R# attributes. IMO using R# annotations is a quick win, whereas writing Roslyn diagnostics is likely to never get done.

**Comment by adamralph** [comment]
Whilst a diagnostic package should be the long term aim (and I'm not convinced it's likely to never get done :wink:), I'd be happy to introduce R# annotations in the meantime. However, we will not be adding `[Pure]` to non-pure methods as a hack. Semantics matter :wink:

**Comment by thomaslevesque** [comment]
I wrote a proof-of-concept analyzer to warn about unused call specifications (i.e. calls to `A.CallTo(...)` where the return value is not used). You can see it here: https://github.com/thomaslevesque/FakeItEasy/commit/5f0e97c0fc70cde06edf3e67484df1fc47806082

**Comment by adamralph** [comment]
Great stuff! I think an analyzer package should be our strategy here.

**Comment by thomaslevesque** [comment]
Yes, it's a good way to provide library-specific guidance. Unfortunately it doesn't help with the original problem that started this issue (R# "implicit capture" warning").

Should I open another issue to discuss other diagnostics that could be added to the analyzer package?

**Comment by blairconrad** [comment]
@thomaslevesque, I think having a set of issues for an analyzer package sounds like a great idea. I say set of, because my preference would be to break the work into small pieces, e.g.:

1. make an analyzer package
2. have the package detect unused call specifications
3. diagnostic 2
4. diagnostic 3  
   …

Thanks for putting your time into this.

**Comment by thomaslevesque** [comment]
That makes sense, I'll create the issues when I have a bit of time.
Also, one thing to consider is that it will be necessary to migrate to VS2015 to be able to develop and use the analyzer... is this going to be problem?

**Comment by blairconrad** [comment]
It may be a problem.
_I_ don't have 2015 yet, so that'll hamper my ability to work on the project. ;)

Really, we should have an issue for moving to VS2015 (and supporting 4.6?) first, and the "analyzer" issue should depend on that issue.

I don't often pay enough attention to the fancy new toys to know what's needed when. For example, I'm not even sure if we'll need to add 4.6 support, or if things will just work.
I should pay more attention, but have been more interested in the 2.0 release (and it's "outdoor work around the house" season where I live, so that sucks up quite a bit of what would normally be FakeItEasy time)…

I'm inclined to think that there's no need for the master branch to require VS2015 until it's released, though. And All of these changes would be going in after the FakeItEasy 2.0 release, which has already taken way longer than I'd initially hoped. (Not complaining - I'm happy with many of the originally unplanned changes we've been putting in.)

**Comment by thomaslevesque** [comment]
> For example, I'm not even sure if we'll need to add 4.6 support, or if things will just work.

It should just work. It's an in-place update for .NET 4.5, and is backward compatible with existing code.

**Comment by adamralph** [comment]
IMHO we definitely shouldn't require VS2015 until it's RTM.

In the meantime, we can create a VS2015 solution, e.g. `FakeItEasy.VS2015.sln` to include the analyzers package.

Agree on the proposed approach above with granular issues.

**Comment by hmemcpy** [comment]
I'll add my 2c, FWIW the problem is the VS SDK dependency, everything else
are nuget packages.
So there isn't a direct reliance on it being VS2015 solution/project...

I hear there are SDK changes coming that will ship only as nuget packages,
no local installation needed.

**Comment by adamralph** [comment]
Thanks @hmemcpy that makes a lot of sense.Let's hope it is the case.

**Comment by ulrichb** [comment]
@adamralph 
> However, we will not be adding [Pure] to non-pure methods as a hack. Semantics matter :wink:

The R# PureAttribute describes that a method has no side-effect (Doc comment: "Indicates that a method does not make any observable state changes").

Invoking `A.CallTo(...)` without following `.Invokes()/.MustHaveHappened()/...` has observable state changes?

**Comment by adamralph** [comment]
@ulrichb I can't say for sure, but perhaps there is indeed no observable state change.

The problem with calling a method pure which does in fact change internal state is the safety of calling it pure is a function of the certainty of that assertion both in the present and the future. How sure are we that the state change is not observable? How sure are we that we can make the same guarantee as the code base evolves?

Given that there is a ubiquitous solution in the pipeline (analyzer packages) I'm reluctant to pursue this.

**Comment by thomaslevesque** [comment]
It _does_ have an observable side effect. Consider this scenario:

```
	var foo = A.Fake<IDisposable>(o => o.Strict());
	foo.Dispose(); // Fails because the call is not configured
```
```
	var foo = A.Fake<IDisposable>(o => o.Strict());
	A.CallTo(() => foo.Dispose());
	foo.Dispose(); // Succeeds because the call is configured
```

So it's definitely not pure.

**Comment by ulrichb** [comment]
@thomaslevesque 
Good example! 

But do we want this behavior? IMO this is pretty surprising. I would prefer the following fake setup in this example: `A.CallTo(() => foo.Dispose()).DoesNothing()`

**Comment by blairconrad** [comment]
@thomaslevesque, as @ulrichb says, excellent example.
@ulrichb, I would argue that we don't want this behaviour, and I was a little surprised as well.

However, whether we want to change the behaviour of `A.CallTo` to remove the observable side effect or not (and I'm not inclined to expend effort on it, to tell you the truth), as @adamralph [says](https://github.com/FakeItEasy/FakeItEasy/issues/56#issuecomment-117811909), we have a ubiquitous solution for the problem you raised (#505) in the pipeline. #490 promises to address the problem without requiring ReSharper (not that I'm against ReSharper).

**Comment by blairconrad** [comment]
Since we have a **wontfix** on this, perhaps we should close it. Objections?

**Comment by thomaslevesque** [comment]
No objections, closing it now.

**Comment by thomaslevesque** [comment]
(actually, it was already closed)

**Comment by blairconrad** [comment]
:blush:
