### ISSUE TITLE
Option for implicit implementation of base interfaces

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#572]
*from https://github.com/FakeItEasy/FakeItEasy/issues/533 raised by @dotnerdify*

Currently, a fake effectively implements each interface in an inheritance tree explicitly, as evidenced by:

```C#
var derived = A.Fake<IDerived>();
A.CallTo(() => derived.Foo).Returns(123);
IBase @base = derived;
@base.Foo.Should().Be(0);

public interface IDerived : IBase
{
    new int Foo{ get; }
}

public interface IBase
{
    int Foo{ get; }
}
```

We should introduce an option for the fake to implement all members in the tree with matching signatures in a single member, i.e.

```C#
@base.Foo.Should().Be(123);
```

**Comment by thomaslevesque** [comment]
As I proposed in the other discussion, it could be something like this:

    A.CallTo(() => derived.Foo).OrHiddenBaseDefinition().Returns(123);

**Comment by adamralph** [comment]
Given that it's effectively changing the shape of the fake, I think it should be an option on fake creation, rather than individual method configuration. Whilst this restricts the fake to all or nothing WRT to members, it would be strange to do something like:

```C#
A.CallTo(() => derived.Foo).OrHiddenBaseDefinition().Returns(123);
A.CallTo(() => derived.Foo).Returns(456);
```

since then the shape of the fake would effectively change between calls to `Foo`.

**Comment by thomaslevesque** [comment]
> Given that it's effectively changing the shape of the fake

Not really... It's changing the shape of the fake _with regard to a given member_. It's perfectly reasonable (and common) to implement one member explicitly, and another implicitly.

IMO, in any reasonable case of hiding a member of the base interface, the new member should actually have a different purpose than the base member, otherwise why would you hide the base member with a new identical one? In other words, if `IBase.Foo` and `IDerived.Foo` really are the same thing, then `IDerived.Foo` shouldn't exist at all. So if you hit a case where you want `IBase.Foo` and `IDerived.Foo` to do the same thing, it's probably a sign that you have a design issue. Based on that, I think it would be strange to say, for a whole fake object, that you want both members to be treated as one, when they really should be different.

So I think we should provide the option, but on a case-by-case basis.

> Whilst this restricts the fake to all or nothing WRT to members, it would be strange to do something like:
> 
>     A.CallTo(() => derived.Foo).OrHiddenBaseDefinition().Returns(123);
>     A.CallTo(() => derived.Foo).Returns(456);
> 
> since then the shape of the fake would effectively change between calls to Foo.

I'm not sure the user would think of it in term of changing shape. The way I see it, using `OrHiddenBaseDefinition` would basically be the same as configuring both the base and derived members., so in your example, it would achieve the same result as this:

    A.CallTo(() => derived.Foo).Returns(123);
    A.CallTo(() => ((IBase)derived).Foo).Returns(123);
    A.CallTo(() => derived.Foo).Returns(456);

With this configuration, `IBase.Foo` would always return 123, while `IDerived.Foo` would return 456 then 123. It doesn't seem really strange to me.

**Comment by blairconrad** [comment]
> it would achieve the same result as this:
> 
> ```c#
> …
> A.CallTo(() => ((IBase)derived).Foo).Returns(123);
> …
> ```

Maybe I'm crazy, but I prefer this notation to 

```c#
A.CallTo(() => derived.Foo).OrHiddenBaseDefinition().Returns(123);
```

Aside from liking the way it looks, now I'm wondering what happens when we have `IBase`, `IMiddle`, `IDerived`. Will we be in a situation where from `IDerived` we don't know whether the `HiddenBaseDefinition` is on `IBase` or `IMiddle`?

**Comment by thomaslevesque** [comment]
> Aside from liking the way it looks, now I'm wondering what happens when we have IBase, IMiddle, IDerived. Will we be in a situation where from IDerived we don't know whether the HiddenBaseDefinition is on IBase or IMiddle?

Well, technically it could be on both, if you inherit two interfaces that have the same member. But it doesn't really matter, if we just say that we configure the call for this member and all hidden base definitions.
Perhaps the method should be named `OrHiddenBaseDefinitions` (plural) to account for the fact that there might be several base definitions.

**Comment by blairconrad** [comment]
I'm a little missing something. It may be that I'm not thinking deeply enough about this, but mightn't someone want _three_ different behaviours?

**Comment by adamralph** [comment]
> Not really... It's changing the shape of the fake with regard to a given member. It's perfectly reasonable (and common) to implement one member explicitly, and another implicitly.

Yes, but you would not expect the type definition to change between two calls to a member :smile:.

However:

> I'm not sure the user would think of it in term of changing shape. The way I see it, using OrHiddenBaseDefinition would basically be the same as configuring both the base and derived members., so in your example, it would achieve the same result as this:

That's a reasonable way to think about it, and I agree. So this means that we are, in fact, always explicitly implementing the base members, but this just becomes a shortcut for configuring both in one go.

However:

> Will we be in a situation where from IDerived we don't know whether the HiddenBaseDefinition is on IBase or IMiddle?

This is a valid point. I'm starting to think the benefit of this syntactic sugar might be outweighed by the awkwardness of conveying the semantics correctly.

**Comment by thomaslevesque** [comment]
> Mightn't someone want three different behaviours?

Sure, and nothing prevents you from doing it:

    A.CallTo(() => derived.Foo).Returns(1);
    A.CallTo(() => ((IMiddle)derived).Foo).Returns(2);
    A.CallTo(() => ((IBase)derived).Foo).Returns(3);

**Comment by blairconrad** [comment]
Yes, I thought that was what I was arguing for over `OrHiddenBaseDefinitions`. But I'm kind of confused by the whole conversation!

**Comment by thomaslevesque** [comment]
> Yes, I thought that was what I was arguing for over OrHiddenBaseDefinitions. But I'm kind of confused by the whole conversation!

Me too... I'm not even sure anymore what we're trying to do here ;)

If you prefer to configure each member explicitly rather than using `OrHiddenBaseDefinitions`, it's already possible now. So what do you think we should do? I thought we had agreed that the current default behavior should be kept (see @patrik-hagne's [comment](https://github.com/FakeItEasy/FakeItEasy/issues/533#issuecomment-170263930) and @adamralph's answer)

**Comment by adamralph** [comment]
I'm not sure we need to do anything. The case of an interface member hiding an identical base member is an edge case, and I can't really see why anyone would do it.

**Comment by blairconrad** [comment]
I'm not sure why one would either.
If @thomaslevesque's `A.CallTo(() => ((IBase)derived).Foo).Returns(123)` example works, I'd leave everything as is.

**Comment by thomaslevesque** [comment]
I think it's the best option. Anything else would only introduce more confusion.
