### ISSUE TITLE
Remove NuGet.Commandline from packages.config

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#616]
Per @tillig in https://github.com/FakeItEasy/FakeItEasy/pull/613#issue-136232159:

> I had a problem building where NuGet package restore was trying to restore NuGet.CommandLine at the solution level... but was using a version of that already checked in. I was getting an error as it tried to restore the package over the top of itself (file locking) so I removed that from the packages.config. It's checked into the repo anyway, so I don't think it needs to be restored each time.

I recently had this problem as well.

**Comment by adamralph** [comment]
It's bizarre because this bug was introduced in 3.0 and supposedly fixed in 3.3.

Since we moved from 2.8 directly to 3.3 I've never had this problem. It seems it may be intermittent though, and perhaps somewhat environment-dependent, so I'm happy to move to a non-NuGet solution for including NuGet.exe in the repo, similar to what I did in xbehave - https://github.com/xbehave/xbehave.net/tree/dev/src/.nuget

**Comment by thomaslevesque** [comment]
> I'm happy to move to a non-NuGet solution for including NuGet.exe in the repo, similar to what I did in xbehave - https://github.com/xbehave/xbehave.net/tree/dev/src/.nuget

:+1:
