### ISSUE TITLE
Test failures after upgrade NUnit to v3

### ISSUE THREAD

**Issue by jeremymeng** [FakeItEasy/FakeItEasy#631]
In order to be able to test the .NET Core porting changes I upgrade NUnit to v3 in [nunit3 branch of my fork](https://github.com/jeremymeng/FakeItEasy/tree/nunit3).  After the upgrade there are one failed and one invalid test.

1. https://github.com/jeremymeng/FakeItEasy/blob/nunit3/tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/CollectionContainsTests.cs#L25
```
1) Failed : FakeItEasy.Tests.ArgumentConstraintManagerExtensions.CollectionContainsTests.IsValid_should_return_true_for_valid_values(10)
  Expected: True
  But was:  False
at FakeItEasy.Tests.ArgumentConstraintTestBase.IsValid_should_return_true_for_valid_values(Object validValue) in C:\github\jeremymeng\FakeItEasy\tests\FakeItEasy.Tests\ArgumentConstraintTestBase.cs:line 39
```
This seems a NUnit v3 bug. I raised https://github.com/nunit/nunit/issues/1375.

**What's** your general practice for failed tests due to external bugs?  If ignoring, how do you track to re-enable it later?

1. https://github.com/jeremymeng/FakeItEasy/blob/nunit3/tests/FakeItEasy.Tests/ServiceLocatorTests.cs#L45
  There are no values from the `NonSingletonTypes` (`Enumerable.Empty<Type>()`).  It seems that NUnit v2.6.4 won't execute this test, while NUnit v3 reports an invalid test with the message

**Any ideas?**

```
2) Invalid : FakeItEasy.Tests.ServiceLocatorTests.Should_be_registered_as_non_singleton
No arguments were provided
```

Thanks!

**Comment by blairconrad** [comment]
@jeremymeng, thanks for your continued work on this.

Regarding `IsValid_should_return_true_for_valid_values`, I don't think we've had a general practice for failed tests due to external bugs. Although if we were to do anything, my inclination would be, since in theory care about the test, to work around it. Perhaps by splitting that test case out. Sure, the code won't be as pretty, but we'd get the coverage we want.

As far as `Should_be_registered_as_non_singleton` goes, I when I was working on #525, I noticed the odd behaviour around empty `TestCaseSource`s and worked around (e.g. in [ArgumentValueFormatterTests.Built_in_formatters_should_have_lower_than_default_priority](https://github.com/FakeItEasy/FakeItEasy/blob/14f149d21b1ecd2f13e06c0cec7a94b3f7682e37/tests/FakeItEasy.Tests/Core/ArgumentValueFormatterTests.cs#L148) just by directly looking at what the test case source would've returned. This was necessary because we wanted to future-proof against new cases being added in the future, and so we're dynamically discovering the test cases.

However, in the case of `FakeItEasy.Tests.ServiceLocatorTests.Should_be_registered_as_non_singleton, we have knowledge of the cases. I'd say we should either provide at least one representative non-singleton case, or we should remove the test altogether.

However, all of this may be moot, as we're working to fix tests under NUnit 3, and we plan to target xUnit, as you've noted in comments on #545. I can start working on that on the side and then we can focus our energies on the code as it's likely to be in the future.

**Comment by jeremymeng** [comment]
Thanks @blairconrad ! The NUnit v3 bug is known and has been fixed.  Next CTP would contain the fix.  I think I will probably leave the test failing.  I don't intend to merge the NUnit v3 upgrade back because of the planned xUnit migration.  I can just use them to help fix porting bugs.

**Comment by adamralph** [comment]
@jeremymeng is there any more to discuss here or can we close the issue?

**Comment by jeremymeng** [comment]
@adamralph Nope. All good.
