### ISSUE TITLE
Use a shared project

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#671]
Instead of manually linking all the files from FakeItEasy to FakeItEasy.Net35.

I guess we'll end up with three projects, FakeItEasy (shared), FakeItEasy.Net35 and FakeItEasy.Net40.

We've been talking about this a bit over at https://github.com/FakeItEasy/FakeItEasy/pull/669#issuecomment-210698166

**Comment by adamralph** [comment]
I've been thinking about doing this when I have some spare cycles but if anyone wants to pick it up in the meantime, please feel free. I guess we do have [bigger fish to fry](https://github.com/FakeItEasy/FakeItEasy/milestones/2.0.0) right now though.

**Comment by thomaslevesque** [comment]
> I've been thinking about doing this when I have some spare cycles but if anyone wants to pick it up in the meantime, please feel free.

Perhaps it would be better to wait until we don't have any large PR in progress, since it's likely to cause messy conflicts.

**Comment by adamralph** [comment]
Good point

**Comment by thomaslevesque** [comment]
Since we dropped 3.5 support, we no longer have code shared between projects. Should we close this issue?

**Comment by blairconrad** [comment]
I see your point. I expect we'll need something at some point for .NET Core (and/or 4.5, if we decide to go that route, which I think is looking less likely), but that could be a new issue.
If nothing else, once we support .NET Core, I think all of our tests should run against all platforms, instead of like what we had for the old 3.5 tests, which tested almost nothing.
Maybe shared projects will be the answer then, or maybe not. I'm good for closing.

**Comment by thomaslevesque** [comment]
I'm not sure we'll need it for .NET Core; `project.json` doesn't specify the list of files, it just includes all source files in the folder. Even though `project.json` is being dropped in favor of an MSBuild solution (a good old .csproj file), MS has hinted that it will no longer be necessary to list the files in the project.

Anyway, I'm closing this issue for now. We can always reopen it later if necessary.
