### ISSUE TITLE
AssignsOutAndRefParameters on delegate proxies

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#677]
Inspired by https://twitter.com/th0maswe1ss/status/723799176941699072.

`AssignsOutAndRefParameters` appears not to work for faked delegates.
[`FakeItEasy.Tests.Creation.DelegateProxies.DelegateProxyGeneratorTests.Should_return_proxy_where_out_parameter_can_be_set`](https://github.com/FakeItEasy/FakeItEasy/blob/126d6056334227cda86eeded31df36b60378cf70/tests/FakeItEasy.Tests/Creation/DelegateProxies/DelegateProxyGeneratorTests.cs#L154) has been `Ignore`d since the project came to GitHub.

If there's a way to enable assigning of out and ref parameters for faked delegates, I think we should do it.
If not, we should document the lack and provide an error when it's attempted.

**Comment by thomaslevesque** [comment]
I'm not sure I understand the scenario you have in mind... Could you give an example?

**Comment by blairconrad** [comment]
Something like this, I suppose

https://gist.github.com/blairconrad/1570c29c831cab9c598926b25c7f171e

The delegate could refer to `Dictionary<string,string>.TryGet`, if one wanted.

**Comment by adamralph** [comment]
To clarify, currently, the `out`/`ref` parameter remains with its default value.

**Comment by thomaslevesque** [comment]
Ah, I see. Shouldn't it be considered a bug?

**Comment by adamralph** [comment]
Perhaps, yes. Is there anything specific in the docs about delegates? I couldn't find anything. I actually didn't even realise they could be faked. I don't think I'd ever tried before.

**Comment by thomaslevesque** [comment]
I just had a look at the code. I think we could fix it, but only in .NET 4.0+, or without using Linq expressions.

Basically, if we have a delegate like this:

    delegate int Foo(int x, ref int y, out int z);

We generate a method like this:

    void ProxyFoo(int x, ref int y, out int z)
    {
        var parametersCastToObject = new[]{ (object)x, (object)y, (object)z };
        return (int)eventRaiser.Raise(parametersCastToObject);
    }

So, the `parametersCastToObject` might be assigned, but we never copy them back to the actual ref/out parameters.

We could add the assignments to generate a method like this instead:

    void ProxyFoo(int x, ref int y, out int z)
    {
        var parametersCastToObject = new[]{ (object)x, (object)y, (object)z };
        var result = (int)eventRaiser.Raise(parametersCastToObject);
        y = (int)parametersCastToObject[1];
        z = (int)parametersCastToObject[2];
        return result;
    }

But `Expression.Assign` is not available in .NET 3.5... So we have the following alternatives
1. drop support for 3.5 (*)
2. support out and ref parameter for faked delegates only in 4.0+
3. generate the method with Reflection.Emit instead of Linq expressions

I'm in favor of option 3. The code to generate is simple enough, so it shouldn't be too hard. I'm willing to give it a try.

(*) there seems to be more and more arguments in favor of dropping 3.5... we should make a list to help us come to a decision.

**Comment by adamralph** [comment]
> there seems to be more and more arguments in favor of dropping 3.5... we should make a list to help us come to a decision.

Yes, and that list should exist in the issue description of https://github.com/FakeItEasy/FakeItEasy/issues/217.

**Comment by adamralph** [comment]
> I'm in favor of option 3. The code to generate is simple enough, so it shouldn't be too hard. I'm willing to give it a try.

Sounds good to me.

**Comment by thomaslevesque** [comment]
Now that we're dropping .NET 3.5, the fix is much easier.
It's ready in this commit : https://github.com/thomaslevesque/FakeItEasy/commit/5570756fa1dbefc872804ad7a80bf3ad87aa9f5d
But I can't create a PR yet, because it requires #687 to be merged first.

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
