### ISSUE TITLE
FakeItEasy.FluentAssertions package

### ISSUE THREAD

**Issue by danielmarbach** [FakeItEasy/FakeItEasy#72]
Maybe this is too much overhead for a simple benefit but I'm dumping it here anyway as an idea. Just thought it might be cool to support fluent assertions which would allow to use their exception and assertion model. The one could use: 

``` csharp
A.CallTo().Should().HaveHappened().And.ExactlyOnce()
```

This would also help to spread the usage of FluentAssertions

**Comment by blairconrad** [comment]
I'm not sure there's much benefit here. It's an interesting suggestion, but there's been no action since it was originally proposed 4 years ago last week. And I (party-pooper that I am) am not interested in supporting an additional syntax for assertions. Lately augmenting the one syntax we have has been a near-Herculean task (mostly undertaken by @thomaslevesque).

Proposal: close **wontfix**.

**Comment by thomaslevesque** [comment]
Well, it's fairly easy to get the basic features (`MustHaveHappened`/`MustNotHaveHappened`) working:

```
public static class FakeItEasyFluentAssertionsExtensions
{
    public static FakeItEasyCallAssertions Should(this IAssertConfiguration configuration)
    {
        return new FakeItEasyCallAssertions(configuration);
    }
}

public class FakeItEasyCallAssertions : ReferenceTypeAssertions<IAssertConfiguration, FakeItEasyCallAssertions>
{
    private IAssertConfiguration _configuration;
    
    public FakeItEasyCallAssertions(IAssertConfiguration configuration)
    {
        _configuration = configuration;
    }
    
    protected override string Context
    {
        get { return "call"; }
    }
    
    public void HaveHappened(Repeated repeatConstraint = null)
    {
        _configuration.MustHaveHappened(repeatConstraint ?? Repeated.AtLeast.Once);
    }
    
    public void NotHaveHappened()
    {
        _configuration.MustNotHaveHappened();
    }
}

...

A.CallTo(() => foo.Bar(42)).Should().HaveHappened(Repeated.Exactly.Twice);

```

That being said, I'm not sure it's worth the trouble...

👍 to close as `wontfix`

**Comment by adamralph** [comment]
Leaving it to the community to spin up a package for this, if desired.

**Comment by ChristoWolf** [comment]
Hi!

Maybe I can give a few more reasons why something like this could be useful:
- FluentAssertions' `AssertionScope` does not aggregate `FakeItEasy.ExpectationException`. Wrapping those would enable this.
- Test frameworks do not recognize `FakeItEasy.ExpectationException` as assertion failures (e.g. [MSTest's AssertFailedException](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.assertfailedexception) but only as some exception.
- Some compatibility with FluentAssertions' `AndConstraint`.
- Assertion API consistency.
- And probably even more.
I got some of it working, but I'm having issues with aggregating ordered assertions failures in `AssertionScope`s.

**Comment by ChristoWolf** [comment]
Hi @blairconrad!

> I do not understand what this means, nor why this is a problem.

Let me give you an example:
```csharp
var fake = A.Fake<IFakeable>();
fake.SomeMethod(1);
using var _ = new AssertionScope();
A.CallTo(() => fake.SomeMethod(0)).MustHaveHappened();
A.CallTo(() => fake.SomeMethod(1)).MustNotHaveHappened();
```
Although the above are inside an `AssertionScope`, the test will already fail at `MustHaveHappened()`, because the `AssertionScope` does not aggregate other exceptions than ones with the test framework's failure assertions.
This means that the `MustNotHaveHappened();` expectation above would never be executed which leads to defect masking.

> I take it this means that some frameworks record the tests as having an error rather than a failure?

I am not sure what you mean by error, can you elaborate?

> Can you expand? What's missing? How would compatibility help?

I have implemented a solution approach, there is no need for something like this, as I simply want to assert on the call expectation.

> Sounds like you're interested in writing a package that would fill the gap.

As I already have a solution, I could of course publish it :)
I will do so when I have some time!

**Comment by blairconrad** [comment]
> > I take it this means that some frameworks record the tests as having an error rather than a failure?

> I am not sure what you mean by error, can you elaborate?

Oh, maybe this isn't a thing anymore. Once upon a time I was using a test framework (maybe very early NUnit?) and tests could do one of 3 things:

1. pass (I think this is clear)
2. fail due to one of the framework's assertion exceptions being thrown
3. error when an unanticipated exception were thrown; something not of the framework

Regarding `AssertionScope`, thanks for the example. I wasn't aware of it. I _have_ used assertj's [soft assertions](https://eliasnogueira.com/soft-asserts-why-should-you-use-them-for-unit-and-integration-tests/), though, and find them useful. I can see the appeal.
