### ISSUE TITLE
Better way to configure calls to generic methods

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#743]
This is related to #648, but not exactly the same, as it also concerns with argument validation rather than return value configuration.

Suppose I have something like this:

```c#
public interface ILogger { /* actual members are not relevant here */ }
public interface ILoggerFactory
{
    ILogger CreateLogger<T>();
}
```

If I want to configure a fake `ILoggerFactory` to return a custom logger for any `T`, the only way is to do this:

```c#
A.CallTo(fakeLoggerFactory)
    .Where(call => call.Method.Name == nameof(ILoggerFactory.CreateLogger) && call.Method.IsGenericMethod)
    .WithReturnType<ILogger>()
    .ReturnsLazily(call => new MyCustomLogger(call.Method.GetGenericArguments()[0]));
```

This isn't very practical... A better syntax would be something like this:

```c#
A.CallTo(() => fakeLoggerFactory.CreateLogger<object>())
    .WithAnyTypeArguments()
    .ReturnsLazily(call => new MyCustomLogger(call.GenericTypeArguments[0]));
```
- `WithAnyTypeArguments` is the same as `WithAnyArguments`, but for generic type arguments.
- `IFakeObjectCall.GenericTypeArguments` is not strictly necessary, it's just a shortcut for `call.Method.GetGenericArguments()`

**Comment by thomaslevesque** [comment]
We could also consider adding a `WhenTypeArgumentsMatch` method, similar to `WhenArgumentsMatch` but for generic type arguments.

(disclaimer : I don't know yet if any of this is actually feasible...)

**Comment by blairconrad** [comment]
@thomaslevesque, have you seen https://github.com/FakeItEasy/FakeItEasy/issues/205#issuecomment-179182646?
I think that where I said

> we could still explore providing open generic methods, if there's interest.

I meant

> we could still explore providing **ways to specify** open generic methods, if there's interest.

Which sounds like what you're talking about now.
If I'm on-base, I like your new issue better, and suggest that we close #205 with a note to look here.

**Comment by thomaslevesque** [comment]
Yes, I saw this comment while looking for an existing issue. It didn't seem to be exactly the same problem, so I opened a new one, but what you said in your comment is indeed what I'm talking about.

**Comment by blairconrad** [comment]
This issue has gotten some interest, largely due to #1884 being asked.

It's probably time to start working on it!

What do we want to provide? Here are possibilities that come to mind:

1. an argument constraint that will match an argument of any type (and value)
2. an argument constraint that will match an argument of any type and that allows further constraints via a `.That`-like syntax as in [More convenience matchers](https://fakeiteasy.readthedocs.io/en/stable/argument-constraints/#more-convenience-matchers)?
3. an argument constraint that constraints by type (is subclass of, is value type, is reference type, ...)
4. Oh, probably a combination of 3 and 4

I think the first is a must-have, if we're going to do anything at all. The rest may be desirable, but I'm just firing stuff off the top of my head here. Also, we don't have to do everything at once, but it might be a good idea to at least think of the syntax we'd have for potential expansion, even if we just go with the basic case for now.

**Comment by thomaslevesque** [comment]
I attempted to implement this a while ago, and encountered some serious roadblocks. Doing this would require some _major_ refactoring, for a rather limited benefit.

The main (only?) use case we've seen so far is to assert calls to `ILogger`. However, since the commonly used logging methods are extension methods, we can't assert them directly, we need to assert the actual `ILogger.Log method` instead. So even if `FormattedLogValues` was public, or if we had something like Moq's `It.IsAnyType`, it would still be pretty inconvenient.

A better approach for testing logging is to use a fake logger that records the log entries. Microsoft provides one [here](https://github.com/dotnet/extensions/tree/main/src/Libraries/Microsoft.Extensions.Diagnostics.Testing).

Closing this for now. We can reopen if there's legitimate interest for it.
