### ISSUE TITLE
Remove Unnatural fakes

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#777]
```C#
var fake = new Fake<IFoo>();
fake.CallsTo(x => x.Bar("some argument")).Returns("some return value");

var foo = fake.FakeObject;
```

I'm guessing that almost no one uses them and this is just cruft in our code base.

**Comment by adamralph** [comment]
@ploeh I see you use unnatural fakes for [AutoFakeItEasy](https://github.com/AutoFixture/AutoFixture/blob/5ff8ec65069324cbc4fc4bf936ca500d06107c6b/Src/AutoFakeItEasy/FakeItEasyMethodQuery.cs#L77-L78) but you also use the "natural" syntax for [AutoNSubstitute](https://github.com/AutoFixture/AutoFixture/blob/5ff8ec65069324cbc4fc4bf936ca500d06107c6b/Src/AutoNSubstitute/NSubstituteMethodQuery.cs#L65) so I assume it would be relatively easy to switch to using `A.Fake<T>` for AutoFakeItEasy?

**Comment by thomaslevesque** [comment]
I personally don't use unnatural fakes, but for some people it might be a more familiar syntax. As far as I can tell, they're not really a burden to maintain. I think we might as well keep them.

**Comment by adamralph** [comment]
Fair enough, but I also don't want to carry stuff around forever if it's never used. It's a poor syntax compared to `A` so I think we should discourage it by deprecating in 2.x by adding `[Obsolete]`.

If, after they've been deprecated for a while, we've heard no complaints, that pretty much clears the way for us to remove in 3.0.

**Comment by ploeh** [comment]
We use that syntax for AutoNSubstitute because, AFAIK, there's no alternative. To be honest, NSubstitute is constantly causing us problems because it's not object-oriented, and instead uses shared mutable state.

In addition to that, with NSubstitute, [you can't use the type system to distinguish between dynamic mocks, and the polymorphic objects they create](https://github.com/AutoFixture/AutoFixture/issues/132#issuecomment-20299082). This leads to all sort of [related problems](https://github.com/AutoFixture/AutoFixture/issues/637).

Internally, it's most likely possible to code around such issues. The generic code you [link to](https://github.com/AutoFixture/AutoFixture/blob/5ff8ec65069324cbc4fc4bf936ca500d06107c6b/Src/AutoNSubstitute/NSubstituteMethodQuery.cs#L65), however, is part of a generic class that is then created with Reflection. Whether or not one considers that elegant is probably a subjective matter. What's indisputable, though, is that if `Fake<T>` is removed, then _users_ lose the ability to declaratively request Test Doubles from method arguments... but I guess they can always migrate to Moq if they consider that a loss :smiling_imp:

**Comment by adamralph** [comment]
@ploeh thanks for chiming in. It sounds like you have a strong case for keeping `Fake<T>` in which case I'm sure we'll happy to keep it.

> users lose the ability to declaratively request Test Doubles from method arguments

This is interesting. What would be a reason for a method to do so? I would say it's up to the caller whether a real or fake object should be supplied.

**Comment by ploeh** [comment]
Indeed, and as a user, I'd like to be able to do that declaratively by requesting e.g. a `Fake<ReservationsController>` in my unit test argument list. This is the use case that's already [impossible with NSubstitute](https://github.com/AutoFixture/AutoFixture/issues/132).

**Comment by adamralph** [comment]
Ah, I see what you mean know - in the context of something like AutoFakeItEasy injecting in either fakes or real objects are arguments to tests.

Fair enough, I'm convinced that we should keep `Fake<T>`.
