### ISSUE TITLE
Generate please pdf documentation (empty 5 pages now)

### ISSUE THREAD

**Issue by lobster2012-user** [FakeItEasy/FakeItEasy#823]
Thanks.

**Comment by blairconrad** [comment]
Hi, @lobster2012-user. Thanks for expressing an interest.

I'm not entirely sure what you're asking. Could you expand?

**Comment by blairconrad** [comment]
Ah. I think I figured it out. You're talking about the ReadTheDocs docs.

Yeah, we have no PDF documentation because our docs are written in markdown, not using Sphinx.

ReadTheDocs [doesn't support building of PDF from markdown](http://read-the-docs.readthedocs.io/en/latest/builds.html#mkdocs) (because MkDocs doesn't):

> As MkDocs doesn’t support automatic PDF generation, Read the Docs cannot create a
> PDF version of your documentation with the Mkdocs option.

Is that what you were hoping for?

**Comment by lobster2012-user** [comment]
Yes, thanks for answer.

**Comment by blairconrad** [comment]
No worries. It'd be nice to supply it, and there are some issues over at readthedocs and mkdocs about supporting PDF. It may come.
