### ISSUE TITLE
Allow faking of statics and non-virtuals

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#90]
http://osherove.com/blog/2012/7/8/faking-static-methods-in-moq-fakeiteasy-and-nsubstitute-migh.html

A big and perhaps contentious topic but I thought I'd at least get a discussion under way.

**Comment by hmemcpy** [comment]
(2 years later)

Because I can't resist :) 

Coming soon...

![image](https://cloud.githubusercontent.com/assets/601206/10269263/566b45b8-6ada-11e5-84fa-ca5fbf79868e.png)

![image](https://cloud.githubusercontent.com/assets/601206/10269265/5e4c723e-6ada-11e5-9328-a9a6e2510e1f.png)

![image](https://cloud.githubusercontent.com/assets/601206/10269444/e62e4e92-6ae0-11e5-970c-d02df729f06c.png)

**Comment by adamralph** [comment]
Did you manage to work out how to do it as an extension?

**Comment by hmemcpy** [comment]
@adamralph nope, needed a few changes inside FIE :(

**Comment by hmemcpy** [comment]
@adamralph I mean, it's probably possible to hook up externally, I'd still need to expose a few things. But I'm just hacking at the moment...

**Comment by adamralph** [comment]
@hmemcpy how far did you get with this? I don't think there's any enthusiasm to try and build this into FIE, but your POC using {I forget the name of the package} may drive out any extension points that are missing in FIE for someone who wants to swap in a fake generator that allows this capability.

**Comment by hmemcpy** [comment]
@adamralph I spiked something that didn't require any changes in FIE, but rather externally took over the FIE API and substituted own functionality (because... why not? :))
However, due to the lack of interest (and lack of time on my part), I doubt this will progress any further. For almost 2 years this issue was silent, I think the world moved on...

I'm :+1: to close this...

**Comment by adamralph** [comment]
@FakeItEasy/owners shall we close?

**Comment by thomaslevesque** [comment]
@adamralph yes, I think we can close

**Comment by ryanwebjackson** [comment]
@hmemcpy How did you implement this? Do you have a repo where you did so?

In the codebase I'm currently working in, I had to do a fancy workaround (due to dependencies outside of my immediate control) that would have been unnecessary with this functionality.

**Comment by pbrianmackey** [comment]
@ryanwebjackson Note this issue was closed with wontfix label on Feb 7, 2016.  Not sure how as this feature would make FakeItEasy the greatest fake/moq framework in existence for legacy code.

**Comment by macco3k** [comment]
So is this still the current policy? Having to define tons of carbon-copies of all my classes just to please the framework is not something I'm really keen on doing to be honest...

**Comment by blairconrad** [comment]
Hi, @macco3k. Thanks for your interest. The policy has not changed. The fact remains that faking statics and non-virtuals is a very hard problem, and to my knowledge, no non-commercial product has ever implemented it. The scope of work required to implement and support the feature is daunting.

To repeat [an earlier comment](https://github.com/FakeItEasy/FakeItEasy/issues/90#issuecomment-51225820)

> […] the most likely route to seeing this feature implemented is to contribute something, such as a solid design, or even the code. Comments expressing interest are welcome, and do (slightly) increase the feature's weight, but given the perceived effort/benefit ratio of providing the feature, I suspect they will not be enough.

Actually, this is probably too soft. I expect the only way this feature would be implemented would be if a PR showed up. If you've an idea, we'd love to see your pull request. It'd be win-win: FakeItEasy would be even more awesomer, and you wouldn't have to create any additional interfaces.

**Comment by macco3k** [comment]
Thanks for taking the time to reply @blairconrad. What about the hack/approach that @hmemcpy was playing with? Perhaps that could be a good starting point, if he could share his code somewhere I'd be more than happy to learn about it.

**Comment by hmemcpy** [comment]
This issue is nearly 10 years old(!)
I'm no longer doing .NET, but from my perspective - things haven't changed.
To be able to intercept and modify non-virtual/static methods, you'd have to modify the actual JIT-compiled code. Commercial, profiler-based tools like Typemock are doing it with pretending to be a profiler and modifying the IL code just before the JIT, so essentially every mocked method becomes (pseudocode:)
```
if (MockManager.isMocked(methodInfo))
    callMockedMethod(methodInfo)
else
    callRealImplementation(methodInfo)
```

My spike was using a then-available library called CodeCop, which allowed you to intercept and modify a running application without using a profiler (it utilized an API hooking library called EasyHook, wrapping it nicely in a managed API). This allowed me to basically replace FakeItEasy's `A.callTo`, etc, method calls with my own implementation, entirely outside the FakeItEasy library.

Having said this, it's 2022. As far as I know, the only approach still remains to modify execution at runtime using either a profiler (heaviest of them all), an API hooking library (typically unmanaged code, CodeCop is dead, AFAIK), or use an IL-modification library to rewrite all static/sealed methods into virtual at post-compilation (invasive).

Needless to say - these are all *very hard* tasks, and probably the reason nobody did this already. Not to mention that I have no idea about the current technological landscape (i.e. .NET Core) and its challenges.

Personally, [my reply](https://github.com/FakeItEasy/FakeItEasy/issues/90#issuecomment-180997886) from 2016 is still valid - mocking static methods is ultimately a mistake, resulting in brittle tests that mock implementation details. Finally, I no longer believe that mocking and mocking frameworks, in general, are the right approach, preferring manual in-memory implementations instead.

 This issue has been closed since 2016; I suggest it remains closed.

**Comment by hmemcpy** [comment]
P.S. for academic purposes, here's my old (archived) spike. I doubt anything works, but feel free to look and do with it what you will https://github.com/hmemcpy/Sledgehammer
