### ISSUE TITLE
Simplify release process

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#913]
As @adamralph [suggests](https://github.com/FakeItEasy/FakeItEasy/issues/907#issuecomment-261233206):

> I propose we remove this point from all releases:
>
> - de-list pre-release or superseded buggy NuGet packages if present
>
> The problem here is that it the NuGet client can display erratic behaviour in some cases when a de-listed version is installed in a project. E.g. when uninstalling, it can fail if the package has been de-listed. I suggest we only consider de-listing a package version in exceptional circumstances, e.g. installation causing a major security risk, a malicious version hacked into the gallery by a third party. I.e. stuff that will almost certainly never happen.
>
> - post a link to the GitHub Release in each issue in this milestone, with thanks to contributors
> 
> This feels like overkill for pre-releases. The burden of having to do this for every alpha and beta, plus the noise in notifications, may outweigh the benefit. I wonder if it's better to restrict this to RTM only:
>
> - for an RTM release, post a link to the GitHub Release in each issue in this milestone, with thanks to contributors

Sounds good to me.

**Comment by blairconrad** [comment]
Oh!

Also, we've been saying

> attach main nupkg and/or analyzer nupkg, whichever have content to release

but it seems we've every time been attaching both packages, even if there's only a change to one.
I'm good to just attach the changed package, but wanted to make sure you all are too.
If not, we should update this directive.

**Comment by thomaslevesque** [comment]
I'm a bit torn on this... On one hand, it makes sense to not release the analyzer if it hasn't changed. On the other hand, it's nice to have the same version for the library and the analyzer; if I see that I'm referencing FakeItEasy 3.0.0 and FakeItEasy.Analyzer 2.3.1, I'm going to wonder if the analyzer is out of date. Also, if we make a meta-package that includes both the library an analyzer (I think we had discussed this at some point), it will be strange if it references different versions of the packages, and also harder to maintain.

**Comment by blairconrad** [comment]
Yeah, I'm torn too.

One other point: if we end up adding more automation to the release, it's probably easier to deal with all the packages in the same manner.

**Comment by adamralph** [comment]
I don't mind keeping the analyzer releases in lockstep with the main package. @thomaslevesque makes a good point. When either package is ahead of the other, I can see people asking why the other is out of date.

This is tangentially related, but I've been giving some more though recently to whether the packages should't be bundled together. IIRC one of the reasons we were put off from doing this last time was due to the PowerShell turds that are required to support packages.config based installations. With project.json based installations, there is native support for analyzers, and I assume that will carry forward to the csproj reboot that's going to happen with VS 2017. I'm wondering whether, at a time when VS 2017 has been around long enough to be considered mainstream, we should consider combining the packages into one. If we think this might be a good idea then it adds weight to the argument for treating the two packages as one "releasable unit", with the versions matching, and release notes combined, with occasions where the release notes only relate to one of them.

**Comment by thomaslevesque** [comment]
@adamralph good point about analyzers in the new project model. However I think we should keep releasing a package without the analyzer, if only to avoid conflicts with ReSharper's external annotations.
