### ISSUE TITLE
Support Invokes method with 5 arguments

### ISSUE THREAD

**Issue by ar7z1** [FakeItEasy/FakeItEasy#926]
I'd like to call `Invokes` for method with 5 arguments ([IDataRecord.GetBytes](https://msdn.microsoft.com/en-us/library/system.data.idatarecord.getbytes)):
```csharp
A.CallTo(() => dataRecord.GetBytes(10, A<long>._, A<byte[]>._, A<int>._, A<int>._))
 .Invokes((int i, long fieldOffset, byte[] buffer, int bufferOffset, int length) => {
        new Random().NextBytes(buffer);
 }).Returns(16);
```

But `Invokes` doesn't support methods with 5 arguments :-(

**Comment by ar7z1** [comment]
I'll create a PR soon.

**Comment by ar7z1** [comment]
Create a PR #927

**Comment by blairconrad** [comment]
Hi, @ar7z1. Thanks for your interest in FakeItEasy.

However, we've intentionally limited the "convenience" versions of `Invokes`, `Throws`, and so on to 4 arguments. We made this decision both because of the increasing effort involved in maintaining more overloads, and because methods with a large number of arguments are often considered to be poor design.

There's no rule that says "4 is good, 5 is bad", of course, but we consider 4 arguments to be a reasonable cutoff.

You can always use `Invokes` overload that takes a `Action<IFakeObjectCall>` when you need to fake a method that takes more arguments.

**Comment by blairconrad** [comment]
In the absence of a differing opinion from the other owners, I'll close this issue **wontfix**.

**Comment by thomaslevesque** [comment]
Thanks @ar7z1, but I agree with @blairconrad on this; we have to put a limit somewhere. Note that the convenience overloads of `Invokes` are defined as extension methods, so you can always declare more of them in your own code if you need them.

**Comment by adamralph** [comment]
👍 to close.

**Comment by ar7z1** [comment]
Hi, @blairconrad, @thomaslevesque and @adamralph. Thanks for review and comments!

Ok, I'll declare `Invokes` in my code.

**Comment by adamralph** [comment]
@ar7z1 thanks again for the contribution. Even though we didn't accept this proposal, we appreciate your effort.

**Comment by ar7z1** [comment]
@adamralph not at all! :-)
