### ISSUE TITLE
Add a (manual) NuGet deployment option to AppVeyor

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#940]
@thomaslevesque instigated this. We should probably

- [x] add the [NuGet.org environment](https://ci.appveyor.com/environment/12362) to AppVeyor
- [x] try it out in the next release (3.0.0-beta003 and 3.0.0 releases have been updated to suggest this)
- [ ] update the "release issue" checklists to instruct us to do that next time (#990)

**Comment by adamralph** [comment]
If we're going to do this, I wonder if we should start building tags, since then we can just click the tag in the build list when deploying. It would need us to alter our workflow a little though, since we'd need to tag the commit (or do so by creating a GitHub release) and then publish to NuGet.org.

One question though - where should we get the nupkg files for attaching to the GH release? I think direct downloading them from NuGet after pushing them is dangerous, since it mutates the package name casing, and may do other things to the package in transit (in short: I don't trust the "Download" button in the web UI).

**Comment by adamralph** [comment]
BTW - this is also a thing:

![image](https://cloud.githubusercontent.com/assets/677704/20926449/9b4eee58-bbbc-11e6-812e-836bb3ac3d62.png)

**Comment by thomaslevesque** [comment]
> If we're going to do this, I wonder if we should start building tags, since then we can just click the tag in the build list when deploying. It would need us to alter our workflow a little though, since we'd need to tag the commit (or do so by creating a GitHub release) and then publish to NuGet.org.

I guess it would make sense; I don't mind the change in the workflow.

> One question though - where should we get the nupkg files for attaching to the GH release? I think direct downloading them from NuGet after pushing them is dangerous, since it mutates the package name casing, and may do other things to the package in transit (in short: I don't trust the "Download" button in the web UI).

I think they should come from AppVeyor

> BTW - this is also a thing:

Oh, interesting. Does it mean it can automatically attach the artifacts to the release?

**Comment by adamralph** [comment]
> Does it mean it can automatically attach the artifacts to the release?

I'm not sure, but I can't think of any other reason for that deployment provider to exist.

**Comment by blairconrad** [comment]
I think anything we decide to do with the releases and/or building tags should be handled in another issue, and maybe after our switch to GitFlow.
